// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zeye.Sorting.Hub.Infrastructure.Persistence;

#nullable disable

namespace Zeye.Sorting.Hub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SortingHubDbContext))]
    [Migration("20260316184030_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.Parcel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ActualChuteId")
                        .HasColumnType("bigint")
                        .HasColumnName("ActualChuteId");

                    b.Property<string>("BagCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("BagCode");

                    b.Property<long?>("BagId")
                        .HasColumnType("bigint")
                        .HasColumnName("BagId");

                    b.Property<string>("BarCodes")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("BarCodes");

                    b.Property<DateTime?>("CompletedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CompletedTime");

                    b.Property<string>("Coordinate")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("Coordinate");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedTime");

                    b.Property<DateTime>("DischargeTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DischargeTime");

                    b.Property<bool>("HasImages")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("HasImages");

                    b.Property<bool>("HasVideos")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("HasVideos");

                    b.Property<decimal>("Height")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("Height");

                    b.Property<bool>("IsSticking")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsSticking");

                    b.Property<decimal>("Length")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("Length");

                    b.Property<long?>("LifecycleMilliseconds")
                        .HasColumnType("bigint")
                        .HasColumnName("LifecycleMilliseconds");

                    b.Property<string>("ModifyIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("ModifyIp");

                    b.Property<DateTime>("ModifyTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ModifyTime");

                    b.Property<int>("NoReadType")
                        .HasColumnType("int")
                        .HasColumnName("NoReadType");

                    b.Property<long>("ParcelTimestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("ParcelTimestamp");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("int")
                        .HasColumnName("RequestStatus");

                    b.Property<DateTime>("ScannedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ScannedTime");

                    b.Property<string>("SegmentCodes")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("SegmentCodes");

                    b.Property<int?>("SorterCarrierId")
                        .HasColumnType("int")
                        .HasColumnName("SorterCarrierId");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<long>("TargetChuteId")
                        .HasColumnType("bigint")
                        .HasColumnName("TargetChuteId");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.Property<decimal>("Volume")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("Volume");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("Weight");

                    b.Property<decimal>("Width")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("Width");

                    b.Property<string>("WorkstationName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("WorkstationName");

                    b.HasKey("Id");

                    b.HasIndex("BagCode");

                    b.HasIndex("BagId");

                    b.HasIndex("ParcelTimestamp");

                    b.HasIndex("ScannedTime");

                    b.HasIndex("WorkstationName");

                    b.ToTable("Parcels", "dbo");
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.BagInfo", b =>
                {
                    b.Property<long>("BagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("BagId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("BagId"));

                    b.Property<string>("BagCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("BagCode");

                    b.Property<DateTime?>("BaggingTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("BaggingTime");

                    b.Property<long>("ChuteId")
                        .HasColumnType("bigint")
                        .HasColumnName("ChuteId");

                    b.Property<string>("ChuteName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("ChuteName");

                    b.Property<int>("ParcelCount")
                        .HasColumnType("int")
                        .HasColumnName("ParcelCount");

                    b.HasKey("BagId");

                    b.HasIndex("BagCode")
                        .IsUnique();

                    b.HasIndex("ChuteId")
                        .IsUnique();

                    b.ToTable("Bags", "dbo");
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.Parcel", b =>
                {
                    b.HasOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.BagInfo", "BagInfo")
                        .WithMany()
                        .HasForeignKey("BagId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsMany("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.ApiRequestInfo", "ApiRequests", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<int>("ApiType")
                                .HasColumnType("int")
                                .HasColumnName("ApiType");

                            b1.Property<int>("ElapsedMilliseconds")
                                .HasColumnType("int")
                                .HasColumnName("ElapsedMilliseconds");

                            b1.Property<string>("Exception")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("varchar(2048)")
                                .HasColumnName("Exception");

                            b1.Property<string>("FormattedMessage")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("varchar(1024)")
                                .HasColumnName("FormattedMessage");

                            b1.Property<string>("Headers")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("varchar(2048)")
                                .HasColumnName("Headers");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<string>("QueryParams")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("varchar(1024)")
                                .HasColumnName("QueryParams");

                            b1.Property<string>("RawData")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("RawData");

                            b1.Property<string>("RequestBody")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("RequestBody");

                            b1.Property<int>("RequestStatus")
                                .HasColumnType("int")
                                .HasColumnName("RequestStatus");

                            b1.Property<DateTime>("RequestTime")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("RequestTime");

                            b1.Property<string>("RequestUrl")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("varchar(512)")
                                .HasColumnName("RequestUrl");

                            b1.Property<string>("ResponseBody")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("ResponseBody");

                            b1.Property<DateTime?>("ResponseTime")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("ResponseTime");

                            b1.HasKey("Id");

                            b1.HasIndex("ApiType");

                            b1.HasIndex("ParcelId");

                            b1.HasIndex("RequestTime");

                            b1.ToTable("Parcel_ApiRequests", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsMany("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.BarCodeInfo", "BarCodeInfos", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<string>("BarCode")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)")
                                .HasColumnName("BarCode");

                            b1.Property<int>("BarCodeType")
                                .HasColumnType("int")
                                .HasColumnName("BarCodeType");

                            b1.Property<DateTime?>("CapturedTime")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("CapturedTime");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.HasKey("Id");

                            b1.HasIndex("BarCode");

                            b1.HasIndex("CapturedTime");

                            b1.HasIndex("ParcelId");

                            b1.ToTable("Parcel_BarCodeInfos", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.ChuteInfo", "ChuteInfo", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<long?>("ActualChuteId")
                                .HasColumnType("bigint")
                                .HasColumnName("ActualChuteId");

                            b1.Property<long?>("BackupChuteId")
                                .HasColumnType("bigint")
                                .HasColumnName("BackupChuteId");

                            b1.Property<DateTime>("LandedTime")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("LandedTime");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<long?>("TargetChuteId")
                                .HasColumnType("bigint")
                                .HasColumnName("TargetChuteId");

                            b1.HasKey("Id");

                            b1.HasIndex("ActualChuteId");

                            b1.HasIndex("ParcelId")
                                .IsUnique();

                            b1.HasIndex("TargetChuteId");

                            b1.ToTable("Parcel_ChuteInfos", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsMany("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.CommandInfo", "CommandInfos", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<int>("ActionType")
                                .HasColumnType("int")
                                .HasColumnName("ActionType");

                            b1.Property<string>("CommandPayload")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("CommandPayload");

                            b1.Property<string>("ConnectionName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)")
                                .HasColumnName("ConnectionName");

                            b1.Property<int>("Direction")
                                .HasColumnType("int")
                                .HasColumnName("Direction");

                            b1.Property<string>("FormattedMessage")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("varchar(1024)")
                                .HasColumnName("FormattedMessage");

                            b1.Property<DateTime>("GeneratedTime")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("GeneratedTime");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<string>("ProtocolName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)")
                                .HasColumnName("ProtocolName");

                            b1.Property<int>("ProtocolType")
                                .HasColumnType("int")
                                .HasColumnName("ProtocolType");

                            b1.HasKey("Id");

                            b1.HasIndex("ActionType");

                            b1.HasIndex("GeneratedTime");

                            b1.HasIndex("ParcelId");

                            b1.ToTable("Parcel_CommandInfos", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.GrayDetectorInfo", "GrayDetectorInfo", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<string>("AttachBoxInfo")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("varchar(2048)")
                                .HasColumnName("AttachBoxInfo");

                            b1.Property<string>("CarrierNumber")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("varchar(64)")
                                .HasColumnName("CarrierNumber");

                            b1.Property<string>("CenterPosition")
                                .HasMaxLength(512)
                                .HasColumnType("varchar(512)")
                                .HasColumnName("CenterPosition");

                            b1.Property<int>("LinkedCarrierCount")
                                .HasColumnType("int")
                                .HasColumnName("LinkedCarrierCount");

                            b1.Property<string>("MainBoxInfo")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("varchar(2048)")
                                .HasColumnName("MainBoxInfo");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<string>("RawResult")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("varchar(2048)")
                                .HasColumnName("RawResult");

                            b1.Property<DateTime>("ResultTime")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("ResultTime");

                            b1.HasKey("Id");

                            b1.HasIndex("CarrierNumber");

                            b1.HasIndex("ParcelId")
                                .IsUnique();

                            b1.ToTable("Parcel_GrayDetectorInfos", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsMany("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.ImageInfo", "ImageInfos", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<string>("CameraName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)")
                                .HasColumnName("CameraName");

                            b1.Property<string>("CameraSerialNumber")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)")
                                .HasColumnName("CameraSerialNumber");

                            b1.Property<int>("CaptureType")
                                .HasColumnType("int")
                                .HasColumnName("CaptureType");

                            b1.Property<string>("CustomName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)")
                                .HasColumnName("CustomName");

                            b1.Property<int>("ImageType")
                                .HasColumnType("int")
                                .HasColumnName("ImageType");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<string>("RelativePath")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("varchar(1024)")
                                .HasColumnName("RelativePath");

                            b1.HasKey("Id");

                            b1.HasIndex("ImageType");

                            b1.HasIndex("ParcelId");

                            b1.ToTable("Parcel_ImageInfos", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.ParcelDeviceInfo", "DeviceInfo", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<string>("CustomName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)")
                                .HasColumnName("CustomName");

                            b1.Property<string>("MachineCode")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)")
                                .HasColumnName("MachineCode");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<string>("WorkstationName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)")
                                .HasColumnName("WorkstationName");

                            b1.HasKey("Id");

                            b1.HasIndex("MachineCode");

                            b1.HasIndex("ParcelId")
                                .IsUnique();

                            b1.ToTable("Parcel_DeviceInfos", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.ParcelPositionInfo", "ParcelPositionInfo", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<decimal>("BackgroundX1")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("BackgroundX1");

                            b1.Property<decimal>("BackgroundX2")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("BackgroundX2");

                            b1.Property<decimal>("BackgroundY1")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("BackgroundY1");

                            b1.Property<decimal>("BackgroundY2")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("BackgroundY2");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("X1")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("X1");

                            b1.Property<decimal>("X2")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("X2");

                            b1.Property<decimal>("Y1")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("Y1");

                            b1.Property<decimal>("Y2")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("Y2");

                            b1.HasKey("Id");

                            b1.HasIndex("ParcelId")
                                .IsUnique();

                            b1.ToTable("Parcel_PositionInfos", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.SorterCarrierInfo", "SorterCarrierInfo", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<decimal>("ConveyorSpeedWhenLoaded")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("ConveyorSpeedWhenLoaded");

                            b1.Property<int>("LinkedCarrierCount")
                                .HasColumnType("int")
                                .HasColumnName("LinkedCarrierCount");

                            b1.Property<DateTime>("LoadedTime")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("LoadedTime");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<int>("SorterCarrierId")
                                .HasColumnType("int")
                                .HasColumnName("SorterCarrierId");

                            b1.HasKey("Id");

                            b1.HasIndex("ParcelId")
                                .IsUnique();

                            b1.HasIndex("SorterCarrierId");

                            b1.ToTable("Parcel_SorterCarrierInfos", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.StickingParcelInfo", "StickingParcelInfo", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<int?>("ElapsedMilliseconds")
                                .HasColumnType("int")
                                .HasColumnName("ElapsedMilliseconds");

                            b1.Property<bool>("IsSticking")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("IsSticking");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<string>("RawData")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("varchar(2048)")
                                .HasColumnName("RawData");

                            b1.Property<DateTime?>("ReceiveTime")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("ReceiveTime");

                            b1.HasKey("Id");

                            b1.HasIndex("ParcelId")
                                .IsUnique();

                            b1.ToTable("Parcel_StickingParcelInfos", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsMany("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.VideoInfo", "VideoInfos", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<int>("Channel")
                                .HasColumnType("int")
                                .HasColumnName("Channel");

                            b1.Property<int>("NodeType")
                                .HasColumnType("int")
                                .HasColumnName("NodeType");

                            b1.Property<string>("NvrSerialNumber")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)")
                                .HasColumnName("NvrSerialNumber");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.HasKey("Id");

                            b1.HasIndex("NodeType");

                            b1.HasIndex("NvrSerialNumber");

                            b1.HasIndex("ParcelId");

                            b1.ToTable("Parcel_VideoInfos", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.VolumeInfo", "VolumeInfo", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<decimal?>("AdjustedHeight")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("AdjustedHeight");

                            b1.Property<decimal?>("AdjustedLength")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("AdjustedLength");

                            b1.Property<decimal?>("AdjustedVolume")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("AdjustedVolume");

                            b1.Property<decimal?>("AdjustedWidth")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("AdjustedWidth");

                            b1.Property<DateTime?>("BindTime")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("BindTime");

                            b1.Property<string>("EvidenceCode")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)")
                                .HasColumnName("EvidenceCode");

                            b1.Property<decimal>("FormattedHeight")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("FormattedHeight");

                            b1.Property<decimal>("FormattedLength")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("FormattedLength");

                            b1.Property<decimal>("FormattedVolume")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("FormattedVolume");

                            b1.Property<decimal>("FormattedWidth")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("FormattedWidth");

                            b1.Property<DateTime>("MeasurementTime")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("MeasurementTime");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<string>("RawVolume")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("varchar(512)")
                                .HasColumnName("RawVolume");

                            b1.Property<int>("SourceType")
                                .HasColumnType("int")
                                .HasColumnName("SourceType");

                            b1.HasKey("Id");

                            b1.HasIndex("ParcelId")
                                .IsUnique();

                            b1.ToTable("Parcel_VolumeInfos", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsMany("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.WeightInfo", "WeightInfos", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<decimal?>("AdjustedWeight")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("AdjustedWeight");

                            b1.Property<string>("EvidenceCode")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)")
                                .HasColumnName("EvidenceCode");

                            b1.Property<decimal>("FormattedWeight")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)")
                                .HasColumnName("FormattedWeight");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<string>("RawWeight")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("varchar(512)")
                                .HasColumnName("RawWeight");

                            b1.Property<DateTime>("WeighingTime")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("WeighingTime");

                            b1.HasKey("Id");

                            b1.HasIndex("ParcelId");

                            b1.HasIndex("WeighingTime");

                            b1.ToTable("Parcel_WeightInfos", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.Navigation("ApiRequests");

                    b.Navigation("BagInfo");

                    b.Navigation("BarCodeInfos");

                    b.Navigation("ChuteInfo");

                    b.Navigation("CommandInfos");

                    b.Navigation("DeviceInfo");

                    b.Navigation("GrayDetectorInfo");

                    b.Navigation("ImageInfos");

                    b.Navigation("ParcelPositionInfo");

                    b.Navigation("SorterCarrierInfo");

                    b.Navigation("StickingParcelInfo");

                    b.Navigation("VideoInfos");

                    b.Navigation("VolumeInfo");

                    b.Navigation("WeightInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
