// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zeye.Sorting.Hub.Infrastructure.Persistence;

#nullable disable

namespace Zeye.Sorting.Hub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SortingHubDbContext))]
    [Migration("20260323045038_UseExternalProvidedParcelId")]
    partial class UseExternalProvidedParcelId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.Parcel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ActualChuteId")
                        .HasColumnType("bigint");

                    b.Property<string>("BagCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<long?>("BagId")
                        .HasColumnType("bigint")
                        .HasColumnName("BagId");

                    b.Property<string>("BarCodes")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<DateTime?>("CompletedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Coordinate")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DischargeTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExceptionType")
                        .HasColumnType("int");

                    b.Property<bool>("HasImages")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasVideos")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Height")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<bool>("IsSticking")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Length")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<long?>("LifecycleMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<string>("ModifyIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("ModifyTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NoReadType")
                        .HasColumnType("int");

                    b.Property<long>("ParcelTimestamp")
                        .HasColumnType("bigint");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScannedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SegmentCodes")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int?>("SorterCarrierId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TargetChuteId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<decimal>("Volume")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("Width")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("WorkstationName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("BagId");

                    b.HasIndex("CreatedTime");

                    b.HasIndex("ParcelTimestamp");

                    b.HasIndex("ScannedTime");

                    b.HasIndex("ActualChuteId", "DischargeTime");

                    b.HasIndex("ActualChuteId", "ScannedTime");

                    b.HasIndex("BagCode", "ScannedTime");

                    b.HasIndex("NoReadType", "ScannedTime");

                    b.HasIndex("RequestStatus", "ScannedTime");

                    b.HasIndex("Status", "ScannedTime");

                    b.HasIndex("TargetChuteId", "ScannedTime");

                    b.HasIndex("WorkstationName", "ScannedTime");

                    b.HasIndex("Status", "ExceptionType", "ScannedTime");

                    b.ToTable("Parcels", (string)null);
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.BagInfo", b =>
                {
                    b.Property<long>("BagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("BagId"));

                    b.Property<string>("BagCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("BaggingTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("ChuteId")
                        .HasColumnType("bigint");

                    b.Property<string>("ChuteName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("ParcelCount")
                        .HasColumnType("int");

                    b.HasKey("BagId");

                    b.HasIndex("BagCode")
                        .IsUnique();

                    b.HasIndex("ChuteId")
                        .IsUnique();

                    b.ToTable("Bags", (string)null);
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.Parcel", b =>
                {
                    b.HasOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.BagInfo", "BagInfo")
                        .WithMany()
                        .HasForeignKey("BagId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsMany("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.ApiRequestInfo", "ApiRequests", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<int>("ApiType")
                                .HasColumnType("int");

                            b1.Property<int>("ElapsedMilliseconds")
                                .HasColumnType("int");

                            b1.Property<string>("Exception")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("varchar(2048)");

                            b1.Property<string>("FormattedMessage")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("varchar(1024)");

                            b1.Property<string>("Headers")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("varchar(2048)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<string>("QueryParams")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("varchar(1024)");

                            b1.Property<string>("RawData")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("RequestBody")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<int>("RequestStatus")
                                .HasColumnType("int");

                            b1.Property<DateTime>("RequestTime")
                                .HasColumnType("datetime(6)");

                            b1.Property<string>("RequestUrl")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("varchar(512)");

                            b1.Property<string>("ResponseBody")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<DateTime?>("ResponseTime")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("Id");

                            b1.HasIndex("ApiType");

                            b1.HasIndex("ParcelId");

                            b1.HasIndex("RequestTime");

                            b1.ToTable("Parcel_ApiRequests", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsMany("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.BarCodeInfo", "BarCodeInfos", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<string>("BarCode")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)");

                            b1.Property<int>("BarCodeType")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("CapturedTime")
                                .HasColumnType("datetime(6)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint")
                                .HasColumnName("ParcelId");

                            b1.HasKey("Id");

                            b1.HasIndex("CapturedTime");

                            b1.HasIndex("ParcelId");

                            b1.HasIndex("BarCode", "ParcelId");

                            b1.ToTable("Parcel_BarCodeInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.ChuteInfo", "ChuteInfo", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<long?>("ActualChuteId")
                                .HasColumnType("bigint");

                            b1.Property<long?>("BackupChuteId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("LandedTime")
                                .HasColumnType("datetime(6)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<long?>("TargetChuteId")
                                .HasColumnType("bigint");

                            b1.HasKey("Id");

                            b1.HasIndex("ActualChuteId");

                            b1.HasIndex("ParcelId")
                                .IsUnique();

                            b1.HasIndex("TargetChuteId");

                            b1.ToTable("Parcel_ChuteInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsMany("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.CommandInfo", "CommandInfos", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<int>("ActionType")
                                .HasColumnType("int");

                            b1.Property<string>("CommandPayload")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("ConnectionName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)");

                            b1.Property<int>("Direction")
                                .HasColumnType("int");

                            b1.Property<string>("FormattedMessage")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("varchar(1024)");

                            b1.Property<DateTime>("GeneratedTime")
                                .HasColumnType("datetime(6)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<string>("ProtocolName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)");

                            b1.Property<int>("ProtocolType")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("ActionType");

                            b1.HasIndex("GeneratedTime");

                            b1.HasIndex("ParcelId");

                            b1.ToTable("Parcel_CommandInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.GrayDetectorInfo", "GrayDetectorInfo", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<string>("AttachBoxInfo")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("varchar(2048)");

                            b1.Property<string>("CarrierNumber")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("varchar(64)");

                            b1.Property<string>("CenterPosition")
                                .HasMaxLength(512)
                                .HasColumnType("varchar(512)");

                            b1.Property<int>("LinkedCarrierCount")
                                .HasColumnType("int");

                            b1.Property<string>("MainBoxInfo")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("varchar(2048)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<string>("RawResult")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("varchar(2048)");

                            b1.Property<DateTime>("ResultTime")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("Id");

                            b1.HasIndex("CarrierNumber");

                            b1.HasIndex("ParcelId")
                                .IsUnique();

                            b1.ToTable("Parcel_GrayDetectorInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsMany("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.ImageInfo", "ImageInfos", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<string>("CameraName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)");

                            b1.Property<string>("CameraSerialNumber")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)");

                            b1.Property<int>("CaptureType")
                                .HasColumnType("int");

                            b1.Property<string>("CustomName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)");

                            b1.Property<int>("ImageType")
                                .HasColumnType("int");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint")
                                .HasColumnName("ParcelId");

                            b1.Property<string>("RelativePath")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("varchar(1024)");

                            b1.HasKey("Id");

                            b1.HasIndex("ImageType");

                            b1.HasIndex("ParcelId");

                            b1.ToTable("Parcel_ImageInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.ParcelDeviceInfo", "DeviceInfo", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<string>("CustomName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)");

                            b1.Property<string>("MachineCode")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint")
                                .HasColumnName("ParcelId");

                            b1.Property<string>("WorkstationName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)");

                            b1.HasKey("Id");

                            b1.HasIndex("MachineCode");

                            b1.HasIndex("ParcelId")
                                .IsUnique();

                            b1.ToTable("Parcel_DeviceInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.ParcelPositionInfo", "ParcelPositionInfo", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<decimal>("BackgroundX1")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("BackgroundX2")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("BackgroundY1")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("BackgroundY2")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint")
                                .HasColumnName("ParcelId");

                            b1.Property<decimal>("X1")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("X2")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("Y1")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("Y2")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.HasKey("Id");

                            b1.HasIndex("ParcelId")
                                .IsUnique();

                            b1.ToTable("Parcel_PositionInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.SorterCarrierInfo", "SorterCarrierInfo", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<decimal>("ConveyorSpeedWhenLoaded")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<int>("LinkedCarrierCount")
                                .HasColumnType("int");

                            b1.Property<DateTime>("LoadedTime")
                                .HasColumnType("datetime(6)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<int>("SorterCarrierId")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("ParcelId")
                                .IsUnique();

                            b1.HasIndex("SorterCarrierId");

                            b1.ToTable("Parcel_SorterCarrierInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.StickingParcelInfo", "StickingParcelInfo", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<int?>("ElapsedMilliseconds")
                                .HasColumnType("int");

                            b1.Property<bool>("IsSticking")
                                .HasColumnType("tinyint(1)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint")
                                .HasColumnName("ParcelId");

                            b1.Property<string>("RawData")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("varchar(2048)");

                            b1.Property<DateTime?>("ReceiveTime")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("Id");

                            b1.HasIndex("ParcelId")
                                .IsUnique();

                            b1.ToTable("Parcel_StickingParcelInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsMany("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.VideoInfo", "VideoInfos", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<int>("Channel")
                                .HasColumnType("int");

                            b1.Property<int>("NodeType")
                                .HasColumnType("int");

                            b1.Property<string>("NvrSerialNumber")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint")
                                .HasColumnName("ParcelId");

                            b1.HasKey("Id");

                            b1.HasIndex("NodeType");

                            b1.HasIndex("NvrSerialNumber");

                            b1.HasIndex("ParcelId");

                            b1.ToTable("Parcel_VideoInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.VolumeInfo", "VolumeInfo", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<decimal?>("AdjustedHeight")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal?>("AdjustedLength")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal?>("AdjustedVolume")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal?>("AdjustedWidth")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<DateTime?>("BindTime")
                                .HasColumnType("datetime(6)");

                            b1.Property<string>("EvidenceCode")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)");

                            b1.Property<decimal>("FormattedHeight")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("FormattedLength")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("FormattedVolume")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("FormattedWidth")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<DateTime>("MeasurementTime")
                                .HasColumnType("datetime(6)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<string>("RawVolume")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("varchar(512)");

                            b1.Property<int>("SourceType")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("ParcelId")
                                .IsUnique();

                            b1.ToTable("Parcel_VolumeInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsMany("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.WeightInfo", "WeightInfos", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<decimal?>("AdjustedWeight")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<string>("EvidenceCode")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)");

                            b1.Property<decimal>("FormattedWeight")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<string>("RawWeight")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("varchar(512)");

                            b1.Property<DateTime>("WeighingTime")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("Id");

                            b1.HasIndex("ParcelId");

                            b1.HasIndex("WeighingTime");

                            b1.ToTable("Parcel_WeightInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.Navigation("ApiRequests");

                    b.Navigation("BagInfo");

                    b.Navigation("BarCodeInfos");

                    b.Navigation("ChuteInfo");

                    b.Navigation("CommandInfos");

                    b.Navigation("DeviceInfo");

                    b.Navigation("GrayDetectorInfo");

                    b.Navigation("ImageInfos");

                    b.Navigation("ParcelPositionInfo");

                    b.Navigation("SorterCarrierInfo");

                    b.Navigation("StickingParcelInfo");

                    b.Navigation("VideoInfos");

                    b.Navigation("VolumeInfo");

                    b.Navigation("WeightInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
