// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zeye.Sorting.Hub.Infrastructure.Persistence;

#nullable disable

namespace Zeye.Sorting.Hub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SortingHubDbContext))]
    partial class SortingHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Zeye.Sorting.Hub.Domain.Aggregates.AuditLogs.WebRequests.WebRequestAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AuditResourceType")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EndedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("HasException")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasRequestBody")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasResponseBody")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsAuthenticated")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRequestBodyTruncated")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsResponseBodyTruncated")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("RequestHost")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("RequestMethod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int>("RequestPayloadType")
                        .HasColumnType("int");

                    b.Property<int?>("RequestPort")
                        .HasColumnType("int");

                    b.Property<string>("RequestRouteTemplate")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("RequestScheme")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<long>("RequestSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("ResponsePayloadType")
                        .HasColumnType("int");

                    b.Property<long>("ResponseSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("SpanId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_WebRequestAuditLogs_CorrelationId");

                    b.HasIndex("TraceId")
                        .HasDatabaseName("IX_WebRequestAuditLogs_TraceId");

                    b.HasIndex("StartedAt", "Id")
                        .HasDatabaseName("IX_WebRequestAuditLogs_StartedAt");

                    b.HasIndex("IsSuccess", "StartedAt", "Id")
                        .HasDatabaseName("IX_WebRequestAuditLogs_IsSuccess_StartedAt");

                    b.HasIndex("OperationName", "StartedAt", "Id")
                        .HasDatabaseName("IX_WebRequestAuditLogs_OperationName_StartedAt");

                    b.HasIndex("RequestPath", "StartedAt", "Id")
                        .HasDatabaseName("IX_WebRequestAuditLogs_RequestPath_StartedAt");

                    b.HasIndex("StatusCode", "StartedAt", "Id")
                        .HasDatabaseName("IX_WebRequestAuditLogs_StatusCode_StartedAt");

                    b.HasIndex("TenantId", "StartedAt", "Id")
                        .HasDatabaseName("IX_WebRequestAuditLogs_TenantId_StartedAt");

                    b.HasIndex("UserId", "StartedAt", "Id")
                        .HasDatabaseName("IX_WebRequestAuditLogs_UserId_StartedAt");

                    b.HasIndex("AuditResourceType", "ResourceId", "StartedAt", "Id")
                        .HasDatabaseName("IX_WebRequestAuditLogs_AuditResourceType_ResourceId_StartedAt");

                    b.ToTable("WebRequestAuditLogs", (string)null);
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Domain.Aggregates.AuditLogs.WebRequests.WebRequestAuditLogDetail", b =>
                {
                    b.Property<long>("WebRequestAuditLogId")
                        .HasColumnType("bigint");

                    b.Property<string>("Accept")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<long>("ActionDurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("AuthorizationType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("CurlCommand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DatabaseAccessCount")
                        .HasColumnType("int");

                    b.Property<long>("DatabaseDurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("DatabaseOperationSummary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ExceptionStackTrace")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("ExtraPropertiesJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FileCount")
                        .HasColumnType("int");

                    b.Property<string>("FileMetadataJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FileOperationType")
                        .HasColumnType("int");

                    b.Property<long>("FileTotalBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("HasDatabaseAccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasFileAccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasImageAccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ImageCount")
                        .HasColumnType("int");

                    b.Property<string>("ImageMetadataJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("MiddlewareDurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("Referer")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RequestBody")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RequestContentType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("RequestHeadersJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RequestQueryString")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RequestUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResourceCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResponseContentType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("ResponseHeadersJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.HasKey("WebRequestAuditLogId");

                    b.HasIndex("StartedAt");

                    b.ToTable("WebRequestAuditLogDetails", (string)null);
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Domain.Aggregates.DataGovernance.ArchiveTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CheckpointPayload")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FailureMessage")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<bool>("IsDryRun")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastAttemptedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PlanSummary")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<long>("PlannedItemCount")
                        .HasColumnType("bigint");

                    b.Property<long>("ProcessedItemCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("int");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<int>("TaskType")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt", "Id");

                    b.HasIndex("TaskType", "CreatedAt", "Id");

                    b.ToTable("ArchiveTasks", (string)null);
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Domain.Aggregates.Events.InboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FailureMessage")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<DateTime?>("LastAttemptedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("SourceSystem", "MessageId")
                        .IsUnique();

                    b.HasIndex("ExpiresAt", "Status", "Id");

                    b.HasIndex("Status", "CreatedAt", "Id");

                    b.ToTable("InboxMessages", (string)null);
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Domain.Aggregates.Idempotency.IdempotencyRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BusinessKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FailureMessage")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("SourceSystem", "OperationName", "BusinessKey", "PayloadHash")
                        .IsUnique();

                    b.ToTable("IdempotencyRecords", (string)null);
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.Parcel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ActualChuteCode")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<long?>("ActualChuteId")
                        .HasColumnType("bigint");

                    b.Property<string>("BagCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<long?>("BagId")
                        .HasColumnType("bigint")
                        .HasColumnName("BagId");

                    b.Property<string>("BarCodes")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<DateTime?>("CompletedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Coordinate")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DetectedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DischargeTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ExceptionType")
                        .HasColumnType("int");

                    b.Property<bool>("HasImages")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasVideos")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("Height")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<bool?>("IsFallbackChuteAssigned")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsRoutingBlocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSticking")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("Length")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<long?>("LifecycleMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MeasurementTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifyIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("ModifyTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NoReadType")
                        .HasColumnType("int");

                    b.Property<long>("ParcelTimestamp")
                        .HasColumnType("bigint");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScannedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SegmentCodes")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<long?>("SorterCarrierId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceExceptionCode")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("SourceInstanceId")
                        .HasMaxLength(96)
                        .HasColumnType("varchar(96)");

                    b.Property<long?>("SourceParcelId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceRunId")
                        .HasMaxLength(96)
                        .HasColumnType("varchar(96)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TargetChuteCode")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<long?>("TargetChuteId")
                        .HasColumnType("bigint");

                    b.Property<string>("TaskCode")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<decimal?>("Volume")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("VolumetricWeightGrams")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(21, 6)
                        .HasColumnType("decimal(21,6)");

                    b.Property<decimal?>("Width")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("WorkstationName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("BagId");

                    b.HasIndex("CreatedTime");

                    b.HasIndex("ParcelTimestamp");

                    b.HasIndex("ActualChuteId", "DischargeTime");

                    b.HasIndex("ScannedTime", "Id");

                    b.HasIndex("ActualChuteId", "ScannedTime", "Id");

                    b.HasIndex("BagCode", "ScannedTime", "Id");

                    b.HasIndex("NoReadType", "ScannedTime", "Id");

                    b.HasIndex("RequestStatus", "ScannedTime", "Id");

                    b.HasIndex("Status", "ScannedTime", "Id");

                    b.HasIndex("TargetChuteId", "ScannedTime", "Id");

                    b.HasIndex("WorkstationName", "ScannedTime", "Id");

                    b.HasIndex("CompletedTime", "Status", "SourceParcelId", "DetectedTime");

                    b.HasIndex("CreatedTime", "Id", "SourceParcelId", "DetectedTime");

                    b.HasIndex("Status", "ExceptionType", "ScannedTime", "Id");

                    b.ToTable("Parcels", (string)null);
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.Processing.ParcelProcessingRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ActualChuteCode")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<string>("Barcode")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("BarcodesJson")
                        .HasColumnType("longtext");

                    b.Property<string>("BindingMode")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<long?>("CandidateSourceParcelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CorrelationId")
                        .HasColumnType("bigint");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<decimal?>("DeltaMilliseconds")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("DispatchedChuteCode")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int?>("ElapsedMilliseconds")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("ExceptionCode")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("FifoRecoveryMode")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long?>("FinalSourceParcelId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("HasReliableFrameBoundary")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("HasReliableTimestamp")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("HeightMm")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("ImageCamera")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ImageContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<bool?>("IsAwaitingWcsDecision")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsFallback")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsRoutingBlocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsSpacingViolation")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsSuccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("LengthMm")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime?>("MeasuredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MessageIdentity")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("ParcelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PartitionTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long?>("PreviousCreationGapMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<string>("Provider")
                        .HasMaxLength(96)
                        .HasColumnType("varchar(96)");

                    b.Property<string>("RawPayload")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RequestAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestBody")
                        .HasColumnType("longtext");

                    b.Property<string>("RequestHeaders")
                        .HasColumnType("longtext");

                    b.Property<string>("RequestUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime?>("ResponseAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("longtext");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("int");

                    b.Property<string>("ScanSequence")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("SourceInstanceId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("varchar(96)");

                    b.Property<long?>("SourceParcelId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceRunId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("varchar(96)");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<string>("TargetChuteCode")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("TaskCode")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("TriggerBatch")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<decimal?>("VolumeMm3")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("VolumetricWeightGrams")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("WeightGrams")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("WidthMm")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("WorkstationName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Key");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("MessageIdentity", "ReceivedAt");

                    b.HasIndex("ParcelId", "OccurredAt");

                    b.HasIndex("ParcelId", "RecordedAt", "Key")
                        .IsDescending(false, true, false);

                    b.HasIndex("SourceInstanceId", "SourceRunId", "SourceParcelId");

                    b.HasIndex("OccurredAt", "IsSuccess", "ParcelId", "Stage");

                    b.HasIndex("SourceInstanceId", "Stage", "PartitionTime", "ParcelId", "OccurredAt", "SourceRunId", "SourceParcelId", "RecordId", "IsSuccess", "HasReliableTimestamp")
                        .HasDatabaseName("IX_Processing_Source_Stage_Duration");

                    b.HasIndex("Stage", "PartitionTime", "ParcelId", "OccurredAt", "SourceInstanceId", "SourceRunId", "SourceParcelId", "RecordId", "IsSuccess", "HasReliableTimestamp")
                        .HasDatabaseName("IX_Processing_Stage_PartitionTime_Duration");

                    b.ToTable("Parcel_ProcessingRecords", (string)null);
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.BagInfo", b =>
                {
                    b.Property<long>("BagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("BagId"));

                    b.Property<string>("BagCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("BaggingTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("ChuteId")
                        .HasColumnType("bigint");

                    b.Property<string>("ChuteName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("ParcelCount")
                        .HasColumnType("int");

                    b.HasKey("BagId");

                    b.HasIndex("BagCode")
                        .IsUnique();

                    b.HasIndex("ChuteId")
                        .IsUnique();

                    b.ToTable("Bags", (string)null);
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Infrastructure.Persistence.Fusion.FusionFactReceipt", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("BodyJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BodySha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("JournalId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("NextProjectionAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ParcelId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("ProjectionAttempts")
                        .HasColumnType("int");

                    b.Property<string>("ProjectionClaimId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("ProjectionClaimUntil")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProjectionError")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProjectionJson")
                        .HasColumnType("longtext");

                    b.Property<string>("ProjectionState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("SourceInstanceId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("varchar(96)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<long>("SourceSequence")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePartitionId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("varchar(96)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("varchar(96)");

                    b.HasKey("Key");

                    b.HasIndex("ProjectionState", "NextProjectionAt");

                    b.HasIndex("SourceInstanceId", "JournalId", "RecordId")
                        .IsUnique();

                    b.HasIndex("SourceInstanceId", "JournalId", "SourceSequence")
                        .IsUnique();

                    b.HasIndex("SourceInstanceId", "ProjectionState", "ProjectionError")
                        .HasDatabaseName("IX_FusionFacts_SourceProgress");

                    b.HasIndex("ProjectionState", "ReceivedAt", "SourceSequence", "NextProjectionAt", "ProjectionClaimUntil")
                        .HasDatabaseName("IX_FusionFacts_ProjectionQueue");

                    b.ToTable("FusionFactReceipts", (string)null);
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Infrastructure.Persistence.Fusion.FusionImageUpload", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("CameraName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ContentSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("IsStored")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("NextOffset")
                        .HasColumnType("bigint");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceImageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("SourceInstanceId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("varchar(96)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<long?>("SourceParcelId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceRunId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("UploadId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Key");

                    b.HasIndex("UploadId")
                        .IsUnique();

                    b.HasIndex("IsStored", "ModifiedAt");

                    b.HasIndex("SourceInstanceId", "SourceImageId")
                        .IsUnique();

                    b.ToTable("FusionImageUploads", (string)null);
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Infrastructure.Persistence.Fusion.FusionJournalHeartbeat", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long>("DroppedUnacknowledgedFacts")
                        .HasColumnType("bigint");

                    b.Property<long>("DroppedUnacknowledgedImages")
                        .HasColumnType("bigint");

                    b.Property<string>("JournalId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<long>("PendingFacts")
                        .HasColumnType("bigint");

                    b.Property<long>("PendingImages")
                        .HasColumnType("bigint");

                    b.Property<bool>("ProtectUnacknowledgedData")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("RejectedFacts")
                        .HasColumnType("bigint");

                    b.Property<long>("RetainedBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SourceInstanceId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("varchar(96)")
                        .UseCollation("utf8mb4_bin");

                    b.HasKey("Key");

                    b.HasIndex("SourceInstanceId", "JournalId")
                        .IsUnique();

                    b.ToTable("FusionJournalHeartbeats", (string)null);
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Infrastructure.Persistence.Fusion.FusionSourceLease", b =>
                {
                    b.Property<string>("SourceInstanceId")
                        .HasMaxLength(96)
                        .HasColumnType("varchar(96)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("JournalId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LeaseId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("SourceInstanceId");

                    b.ToTable("FusionSourceLeases", (string)null);
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Infrastructure.Persistence.Management.ManagedDocument", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.ToTable("ManagedDocuments", (string)null);
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Infrastructure.Persistence.ReadModels.ParcelDurationBackfillState", b =>
                {
                    b.Property<string>("Suffix")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<bool>("Completed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Cursor")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("DwsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DwsCursor")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Suffix");

                    b.ToTable("ParcelDurationBackfillStates", (string)null);
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Infrastructure.Persistence.ReadModels.ParcelDurationCall", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("IsSuccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("Milliseconds")
                        .HasPrecision(20, 4)
                        .HasColumnType("decimal(20,4)");

                    b.Property<long>("ParcelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PartitionTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Provider")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("RequestUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("SampleKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("SourceInstanceId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("varchar(96)");

                    b.Property<long?>("SourceParcelId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceRunId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("varchar(96)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TimingSource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Key");

                    b.HasIndex("ParcelId");

                    b.HasIndex("PartitionTime", "ParcelId");

                    b.HasIndex("SourceInstanceId", "PartitionTime", "ParcelId");

                    b.HasIndex("Type", "PartitionTime", "Milliseconds");

                    b.ToTable("Parcel_DurationCalls", (string)null);
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Infrastructure.Persistence.ReadModels.ParcelDurationFact", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("AttemptId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<int?>("ElapsedMilliseconds")
                        .HasColumnType("int");

                    b.Property<bool?>("HasReliableTimestamp")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsSuccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<long?>("ParcelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PartitionTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Projected")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("RequestAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime?>("ResponseAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Skipped")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SourceInstanceId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("varchar(96)");

                    b.Property<long?>("SourceParcelId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceRunId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("varchar(96)");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<bool>("Transport")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Key");

                    b.HasIndex("ParcelId");

                    b.HasIndex("PartitionTime", "ParcelId");

                    b.HasIndex("Projected", "ParcelId");

                    b.HasIndex("SourceInstanceId", "PartitionTime", "ParcelId");

                    b.ToTable("Parcel_DurationFacts", (string)null);
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Infrastructure.Persistence.Sharding.ParcelLocation", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Suffix")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("SourceKey")
                        .IsUnique();

                    b.ToTable("ParcelLocations", (string)null);
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Infrastructure.Persistence.Sharding.ParcelPartitionCatalogEntry", b =>
                {
                    b.Property<string>("Suffix")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Suffix");

                    b.ToTable("ParcelPartitionCatalog", (string)null);
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Infrastructure.Persistence.Sharding.ParcelProcessingReceipt", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long?>("ParcelId")
                        .HasColumnType("bigint");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Suffix")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Key");

                    b.HasIndex("ParcelId", "RecordedAt");

                    b.ToTable("ParcelProcessingReceipts", (string)null);
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Infrastructure.Persistence.Sharding.PartitionSchemaVersion", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("MigrationId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Key");

                    b.ToTable("PartitionSchemaVersions", (string)null);
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Infrastructure.Queries.ParcelDwsMeasurementSnapshot", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Barcode")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<bool?>("HasReliableTimestamp")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("HeightMm")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<bool?>("IsSuccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("LengthMm")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime?>("MeasuredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MessageIdentity")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("ParcelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PartitionTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("SourceInstanceId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("varchar(96)");

                    b.Property<long?>("SourceParcelId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceRunId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("varchar(96)");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<decimal?>("VolumeMm3")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("WeightGrams")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("WidthMm")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("WorkstationName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Key");

                    b.HasIndex("ParcelId", "Stage");

                    b.HasIndex("PartitionTime", "Stage");

                    b.HasIndex("PartitionTime", "Stage", "IsSuccess")
                        .HasDatabaseName("IX_Dws_Time_Stage_Success");

                    b.HasIndex("SourceInstanceId", "PartitionTime", "Stage");

                    b.ToTable("Parcel_DwsMeasurements", (string)null);
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Domain.Aggregates.AuditLogs.WebRequests.WebRequestAuditLogDetail", b =>
                {
                    b.HasOne("Zeye.Sorting.Hub.Domain.Aggregates.AuditLogs.WebRequests.WebRequestAuditLog", "WebRequestAuditLog")
                        .WithOne("Detail")
                        .HasForeignKey("Zeye.Sorting.Hub.Domain.Aggregates.AuditLogs.WebRequests.WebRequestAuditLogDetail", "WebRequestAuditLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebRequestAuditLog");
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.Parcel", b =>
                {
                    b.HasOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.BagInfo", "BagInfo")
                        .WithMany()
                        .HasForeignKey("BagId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsMany("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.ApiRequestInfo", "ApiRequests", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<int>("ApiType")
                                .HasColumnType("int");

                            b1.Property<int>("ElapsedMilliseconds")
                                .HasColumnType("int");

                            b1.Property<string>("Exception")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("varchar(2048)");

                            b1.Property<string>("FormattedMessage")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("varchar(1024)");

                            b1.Property<string>("Headers")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("varchar(2048)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<string>("QueryParams")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("varchar(1024)");

                            b1.Property<string>("RawData")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("RequestBody")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<int>("RequestStatus")
                                .HasColumnType("int");

                            b1.Property<DateTime>("RequestTime")
                                .HasColumnType("datetime(6)");

                            b1.Property<string>("RequestUrl")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("varchar(512)");

                            b1.Property<string>("ResponseBody")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<DateTime?>("ResponseTime")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("Id");

                            b1.HasIndex("ApiType");

                            b1.HasIndex("ParcelId");

                            b1.HasIndex("RequestTime");

                            b1.ToTable("Parcel_ApiRequests", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsMany("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.BarCodeInfo", "BarCodeInfos", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<string>("BarCode")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)");

                            b1.Property<int>("BarCodeType")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("CapturedTime")
                                .HasColumnType("datetime(6)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint")
                                .HasColumnName("ParcelId");

                            b1.HasKey("Id");

                            b1.HasIndex("CapturedTime");

                            b1.HasIndex("ParcelId");

                            b1.HasIndex("BarCode", "ParcelId");

                            b1.ToTable("Parcel_BarCodeInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.ChuteInfo", "ChuteInfo", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<long?>("ActualChuteId")
                                .HasColumnType("bigint");

                            b1.Property<long?>("BackupChuteId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("LandedTime")
                                .HasColumnType("datetime(6)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<long?>("TargetChuteId")
                                .HasColumnType("bigint");

                            b1.HasKey("Id");

                            b1.HasIndex("ActualChuteId");

                            b1.HasIndex("ParcelId")
                                .IsUnique();

                            b1.HasIndex("TargetChuteId");

                            b1.ToTable("Parcel_ChuteInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsMany("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.CommandInfo", "CommandInfos", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<int>("ActionType")
                                .HasColumnType("int");

                            b1.Property<string>("CommandPayload")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("ConnectionName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)");

                            b1.Property<int>("Direction")
                                .HasColumnType("int");

                            b1.Property<string>("FormattedMessage")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("varchar(1024)");

                            b1.Property<DateTime>("GeneratedTime")
                                .HasColumnType("datetime(6)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<string>("ProtocolName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)");

                            b1.Property<int>("ProtocolType")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("ActionType");

                            b1.HasIndex("GeneratedTime");

                            b1.HasIndex("ParcelId");

                            b1.ToTable("Parcel_CommandInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.GrayDetectorInfo", "GrayDetectorInfo", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<string>("AttachBoxInfo")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("varchar(2048)");

                            b1.Property<string>("CarrierNumber")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("varchar(64)");

                            b1.Property<string>("CenterPosition")
                                .HasMaxLength(512)
                                .HasColumnType("varchar(512)");

                            b1.Property<int>("LinkedCarrierCount")
                                .HasColumnType("int");

                            b1.Property<string>("MainBoxInfo")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("varchar(2048)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<string>("RawResult")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("varchar(2048)");

                            b1.Property<DateTime>("ResultTime")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("Id");

                            b1.HasIndex("CarrierNumber");

                            b1.HasIndex("ParcelId")
                                .IsUnique();

                            b1.ToTable("Parcel_GrayDetectorInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsMany("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.ImageInfo", "ImageInfos", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<string>("BucketName")
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)");

                            b1.Property<string>("CameraName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)");

                            b1.Property<string>("CameraSerialNumber")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)");

                            b1.Property<int>("CaptureType")
                                .HasColumnType("int");

                            b1.Property<string>("ContentType")
                                .HasMaxLength(256)
                                .HasColumnType("varchar(256)");

                            b1.Property<string>("CustomName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)");

                            b1.Property<string>("ETag")
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)");

                            b1.Property<int>("ImageType")
                                .HasColumnType("int");

                            b1.Property<string>("ObjectKey")
                                .HasMaxLength(1024)
                                .HasColumnType("varchar(1024)");

                            b1.Property<long?>("ObjectSizeBytes")
                                .HasColumnType("bigint");

                            b1.Property<string>("OriginalFileName")
                                .HasMaxLength(256)
                                .HasColumnType("varchar(256)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint")
                                .HasColumnName("ParcelId");

                            b1.Property<string>("RelativePath")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("varchar(1024)");

                            b1.Property<string>("Sha256")
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)");

                            b1.Property<int?>("StorageProvider")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("UploadedAtLocal")
                                .HasColumnType("datetime(6)")
                                .HasComment("上传完成时间（本地时间）");

                            b1.HasKey("Id");

                            b1.HasIndex("ImageType");

                            b1.HasIndex("ParcelId");

                            b1.HasIndex("StorageProvider");

                            b1.HasIndex("UploadedAtLocal");

                            b1.HasIndex("BucketName", "ObjectKey")
                                .HasAnnotation("MySql:IndexPrefixLength", new[] { 128, 512 });

                            b1.ToTable("Parcel_ImageInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.ParcelDeviceInfo", "DeviceInfo", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<string>("CustomName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)");

                            b1.Property<string>("MachineCode")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint")
                                .HasColumnName("ParcelId");

                            b1.Property<string>("WorkstationName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)");

                            b1.HasKey("Id");

                            b1.HasIndex("MachineCode");

                            b1.HasIndex("ParcelId")
                                .IsUnique();

                            b1.ToTable("Parcel_DeviceInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.ParcelPositionInfo", "ParcelPositionInfo", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<decimal>("BackgroundX1")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("BackgroundX2")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("BackgroundY1")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("BackgroundY2")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint")
                                .HasColumnName("ParcelId");

                            b1.Property<decimal>("X1")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("X2")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("Y1")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("Y2")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.HasKey("Id");

                            b1.HasIndex("ParcelId")
                                .IsUnique();

                            b1.ToTable("Parcel_PositionInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.SorterCarrierInfo", "SorterCarrierInfo", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<decimal>("ConveyorSpeedWhenLoaded")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<int>("LinkedCarrierCount")
                                .HasColumnType("int");

                            b1.Property<DateTime>("LoadedTime")
                                .HasColumnType("datetime(6)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<long>("SorterCarrierId")
                                .HasColumnType("bigint");

                            b1.HasKey("Id");

                            b1.HasIndex("ParcelId")
                                .IsUnique();

                            b1.HasIndex("SorterCarrierId");

                            b1.ToTable("Parcel_SorterCarrierInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.StickingParcelInfo", "StickingParcelInfo", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<int?>("ElapsedMilliseconds")
                                .HasColumnType("int");

                            b1.Property<bool>("IsSticking")
                                .HasColumnType("tinyint(1)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint")
                                .HasColumnName("ParcelId");

                            b1.Property<string>("RawData")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("varchar(2048)");

                            b1.Property<DateTime?>("ReceiveTime")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("Id");

                            b1.HasIndex("ParcelId")
                                .IsUnique();

                            b1.ToTable("Parcel_StickingParcelInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsMany("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.VideoInfo", "VideoInfos", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<int>("Channel")
                                .HasColumnType("int");

                            b1.Property<int>("NodeType")
                                .HasColumnType("int");

                            b1.Property<string>("NvrSerialNumber")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint")
                                .HasColumnName("ParcelId");

                            b1.HasKey("Id");

                            b1.HasIndex("NodeType");

                            b1.HasIndex("NvrSerialNumber");

                            b1.HasIndex("ParcelId");

                            b1.ToTable("Parcel_VideoInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.VolumeInfo", "VolumeInfo", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<decimal?>("AdjustedHeight")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal?>("AdjustedLength")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal?>("AdjustedVolume")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal?>("AdjustedWidth")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<DateTime?>("BindTime")
                                .HasColumnType("datetime(6)");

                            b1.Property<string>("EvidenceCode")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)");

                            b1.Property<decimal>("FormattedHeight")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("FormattedLength")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("FormattedVolume")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("FormattedWidth")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<DateTime>("MeasurementTime")
                                .HasColumnType("datetime(6)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<string>("RawVolume")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("varchar(512)");

                            b1.Property<int>("SourceType")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("ParcelId")
                                .IsUnique();

                            b1.ToTable("Parcel_VolumeInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsMany("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.WeightInfo", "WeightInfos", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<decimal?>("AdjustedWeight")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<string>("EvidenceCode")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("varchar(128)");

                            b1.Property<decimal>("FormattedWeight")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<string>("RawWeight")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("varchar(512)");

                            b1.Property<DateTime>("WeighingTime")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("Id");

                            b1.HasIndex("ParcelId");

                            b1.HasIndex("WeighingTime");

                            b1.ToTable("Parcel_WeightInfos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.Navigation("ApiRequests");

                    b.Navigation("BagInfo");

                    b.Navigation("BarCodeInfos");

                    b.Navigation("ChuteInfo");

                    b.Navigation("CommandInfos");

                    b.Navigation("DeviceInfo");

                    b.Navigation("GrayDetectorInfo");

                    b.Navigation("ImageInfos");

                    b.Navigation("ParcelPositionInfo");

                    b.Navigation("SorterCarrierInfo");

                    b.Navigation("StickingParcelInfo");

                    b.Navigation("VideoInfos");

                    b.Navigation("VolumeInfo");

                    b.Navigation("WeightInfos");
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Domain.Aggregates.AuditLogs.WebRequests.WebRequestAuditLog", b =>
                {
                    b.Navigation("Detail");
                });
        }
    }
}
