<Project Sdk="Microsoft.NET.Sdk">

  <!-- 中文说明：契约模块的构建与依赖配置。 -->
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="6.1.0" />
  </ItemGroup>

</Project>
