// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zeye.Sorting.Hub.Infrastructure.Persistence;

#nullable disable

namespace Zeye.Sorting.Hub.Infrastructure.SqlServerMigrations.Migrations
{
    [DbContext(typeof(SortingHubDbContext))]
    [Migration("20261006211340_OptimizeUnboundRecordLookupSqlServer")]
    partial class OptimizeUnboundRecordLookupSqlServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Zeye.Sorting.Hub.Domain.Aggregates.AuditLogs.WebRequests.WebRequestAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AuditResourceType")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasException")
                        .HasColumnType("bit");

                    b.Property<bool>("HasRequestBody")
                        .HasColumnType("bit");

                    b.Property<bool>("HasResponseBody")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAuthenticated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequestBodyTruncated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsResponseBodyTruncated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RequestHost")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RequestMethod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("RequestPayloadType")
                        .HasColumnType("int");

                    b.Property<int?>("RequestPort")
                        .HasColumnType("int");

                    b.Property<string>("RequestRouteTemplate")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("RequestScheme")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long>("RequestSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("ResponsePayloadType")
                        .HasColumnType("int");

                    b.Property<long>("ResponseSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("SpanId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_WebRequestAuditLogs_CorrelationId");

                    b.HasIndex("TraceId")
                        .HasDatabaseName("IX_WebRequestAuditLogs_TraceId");

                    b.HasIndex("StartedAt", "Id")
                        .HasDatabaseName("IX_WebRequestAuditLogs_StartedAt");

                    b.HasIndex("IsSuccess", "StartedAt", "Id")
                        .HasDatabaseName("IX_WebRequestAuditLogs_IsSuccess_StartedAt");

                    b.HasIndex("OperationName", "StartedAt", "Id")
                        .HasDatabaseName("IX_WebRequestAuditLogs_OperationName_StartedAt");

                    b.HasIndex("RequestPath", "StartedAt", "Id")
                        .HasDatabaseName("IX_WebRequestAuditLogs_RequestPath_StartedAt");

                    b.HasIndex("StatusCode", "StartedAt", "Id")
                        .HasDatabaseName("IX_WebRequestAuditLogs_StatusCode_StartedAt");

                    b.HasIndex("TenantId", "StartedAt", "Id")
                        .HasDatabaseName("IX_WebRequestAuditLogs_TenantId_StartedAt");

                    b.HasIndex("UserId", "StartedAt", "Id")
                        .HasDatabaseName("IX_WebRequestAuditLogs_UserId_StartedAt");

                    b.HasIndex("AuditResourceType", "ResourceId", "StartedAt", "Id")
                        .HasDatabaseName("IX_WebRequestAuditLogs_AuditResourceType_ResourceId_StartedAt");

                    b.ToTable("WebRequestAuditLogs", "dbo");
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Domain.Aggregates.AuditLogs.WebRequests.WebRequestAuditLogDetail", b =>
                {
                    b.Property<long>("WebRequestAuditLogId")
                        .HasColumnType("bigint");

                    b.Property<string>("Accept")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<long>("ActionDurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("AuthorizationType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CurlCommand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DatabaseAccessCount")
                        .HasColumnType("int");

                    b.Property<long>("DatabaseDurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("DatabaseOperationSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExceptionStackTrace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ExtraPropertiesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FileCount")
                        .HasColumnType("int");

                    b.Property<string>("FileMetadataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FileOperationType")
                        .HasColumnType("int");

                    b.Property<long>("FileTotalBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("HasDatabaseAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("HasFileAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("HasImageAccess")
                        .HasColumnType("bit");

                    b.Property<int>("ImageCount")
                        .HasColumnType("int");

                    b.Property<string>("ImageMetadataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MiddlewareDurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Referer")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestContentType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("RequestHeadersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestQueryString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResourceCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseContentType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ResponseHeadersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("WebRequestAuditLogId");

                    b.HasIndex("StartedAt");

                    b.ToTable("WebRequestAuditLogDetails", "dbo");
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Domain.Aggregates.DataGovernance.ArchiveTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CheckpointPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureMessage")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsDryRun")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastAttemptedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanSummary")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<long>("PlannedItemCount")
                        .HasColumnType("bigint");

                    b.Property<long>("ProcessedItemCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("int");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<int>("TaskType")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt", "Id");

                    b.HasIndex("TaskType", "CreatedAt", "Id");

                    b.ToTable("ArchiveTasks", "dbo");
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Domain.Aggregates.Events.InboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureMessage")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime?>("LastAttemptedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SourceSystem", "MessageId")
                        .IsUnique();

                    b.HasIndex("ExpiresAt", "Status", "Id");

                    b.HasIndex("Status", "CreatedAt", "Id");

                    b.ToTable("InboxMessages", "dbo");
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Domain.Aggregates.Idempotency.IdempotencyRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BusinessKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureMessage")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("SourceSystem", "OperationName", "BusinessKey", "PayloadHash")
                        .IsUnique();

                    b.ToTable("IdempotencyRecords", "dbo");
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.Parcel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ActualChuteCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("ActualChuteId")
                        .HasColumnType("bigint");

                    b.Property<string>("BagCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("BagId")
                        .HasColumnType("bigint")
                        .HasColumnName("BagId");

                    b.Property<string>("BarCodes")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime?>("CompletedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Coordinate")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DetectedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DischargeTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExceptionType")
                        .HasColumnType("int");

                    b.Property<bool>("HasImages")
                        .HasColumnType("bit");

                    b.Property<bool>("HasVideos")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Height")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<bool?>("IsFallbackChuteAssigned")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRoutingBlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSticking")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Length")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<long?>("LifecycleMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MeasurementTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("NoReadType")
                        .HasColumnType("int");

                    b.Property<long>("ParcelTimestamp")
                        .HasColumnType("bigint");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScannedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SegmentCodes")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long?>("SorterCarrierId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceExceptionCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceInstanceId")
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)");

                    b.Property<long?>("SourceParcelId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceRunId")
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TargetChuteCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("TargetChuteId")
                        .HasColumnType("bigint");

                    b.Property<string>("TaskCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<decimal?>("Volume")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("VolumetricWeightGrams")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(21, 6)
                        .HasColumnType("decimal(21,6)");

                    b.Property<decimal?>("Width")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("WorkstationName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("BagId");

                    b.HasIndex("CreatedTime");

                    b.HasIndex("ParcelTimestamp");

                    b.HasIndex("ActualChuteId", "DischargeTime");

                    b.HasIndex("ScannedTime", "Id");

                    b.HasIndex("ActualChuteId", "ScannedTime", "Id");

                    b.HasIndex("BagCode", "ScannedTime", "Id");

                    b.HasIndex("NoReadType", "ScannedTime", "Id");

                    b.HasIndex("RequestStatus", "ScannedTime", "Id");

                    b.HasIndex("Status", "ScannedTime", "Id");

                    b.HasIndex("TargetChuteId", "ScannedTime", "Id");

                    b.HasIndex("WorkstationName", "ScannedTime", "Id");

                    b.HasIndex("CompletedTime", "Status", "SourceParcelId", "DetectedTime");

                    b.HasIndex("CreatedTime", "Id", "SourceParcelId", "DetectedTime");

                    b.HasIndex("Status", "ExceptionType", "ScannedTime", "Id");

                    b.ToTable("Parcels", "dbo");
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.Processing.ParcelProcessingRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ActualChuteCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<string>("Barcode")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("BarcodesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BindingMode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long?>("CandidateSourceParcelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CorrelationId")
                        .HasColumnType("bigint");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<decimal?>("DeltaMilliseconds")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("DispatchedChuteCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("ElapsedMilliseconds")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ExceptionCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FifoRecoveryMode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long?>("FinalSourceParcelId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("HasReliableFrameBoundary")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasReliableTimestamp")
                        .HasColumnType("bit");

                    b.Property<decimal?>("HeightMm")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("ImageCamera")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ImageContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<bool?>("IsAwaitingWcsDecision")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFallback")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRoutingBlocked")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSpacingViolation")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LengthMm")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime?>("MeasuredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageIdentity")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ParcelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PartitionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long?>("PreviousCreationGapMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<string>("Provider")
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)");

                    b.Property<string>("RawPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RequestAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestHeaders")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("ResponseAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("int");

                    b.Property<string>("ScanSequence")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceInstanceId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)");

                    b.Property<long?>("SourceParcelId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceRunId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<string>("TargetChuteCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TaskCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TriggerBatch")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal?>("VolumeMm3")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("VolumetricWeightGrams")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("WeightGrams")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("WidthMm")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("WorkstationName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Key");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("MessageIdentity", "ReceivedAt");

                    b.HasIndex("ParcelId", "OccurredAt");

                    b.HasIndex("ParcelId", "RecordedAt", "Key")
                        .IsDescending(false, true, false);

                    b.HasIndex("SourceInstanceId", "SourceRunId", "SourceParcelId");

                    b.HasIndex("OccurredAt", "IsSuccess", "ParcelId", "Stage");

                    b.ToTable("Parcel_ProcessingRecords", "dbo");
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.BagInfo", b =>
                {
                    b.Property<long>("BagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BagId"));

                    b.Property<string>("BagCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("BaggingTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("ChuteId")
                        .HasColumnType("bigint");

                    b.Property<string>("ChuteName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("ParcelCount")
                        .HasColumnType("int");

                    b.HasKey("BagId");

                    b.HasIndex("BagCode")
                        .IsUnique();

                    b.HasIndex("ChuteId")
                        .IsUnique();

                    b.ToTable("Bags", "dbo");
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Infrastructure.Persistence.Fusion.FusionFactReceipt", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("BodyJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodySha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("JournalId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("NextProjectionAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParcelId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("ProjectionAttempts")
                        .HasColumnType("int");

                    b.Property<string>("ProjectionClaimId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("ProjectionClaimUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectionError")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProjectionJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectionState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SourceInstanceId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<long>("SourceSequence")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePartitionId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)");

                    b.HasKey("Key");

                    b.HasIndex("ProjectionState", "NextProjectionAt");

                    b.HasIndex("SourceInstanceId", "JournalId", "RecordId")
                        .IsUnique();

                    b.HasIndex("SourceInstanceId", "JournalId", "SourceSequence")
                        .IsUnique();

                    b.HasIndex("SourceInstanceId", "ProjectionState", "ProjectionError")
                        .HasDatabaseName("IX_FusionFacts_SourceProgress");

                    b.HasIndex("ProjectionState", "ReceivedAt", "SourceSequence", "NextProjectionAt", "ProjectionClaimUntil")
                        .HasDatabaseName("IX_FusionFacts_ProjectionQueue");

                    b.ToTable("FusionFactReceipts", "dbo");
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Infrastructure.Persistence.Fusion.FusionImageUpload", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CameraName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ContentSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsStored")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("NextOffset")
                        .HasColumnType("bigint");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceImageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("SourceInstanceId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<long?>("SourceParcelId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceRunId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("UploadId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Key");

                    b.HasIndex("UploadId")
                        .IsUnique()
                        .HasFilter("[UploadId] IS NOT NULL");

                    b.HasIndex("IsStored", "ModifiedAt");

                    b.HasIndex("SourceInstanceId", "SourceImageId")
                        .IsUnique();

                    b.ToTable("FusionImageUploads", "dbo");
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Infrastructure.Persistence.Fusion.FusionJournalHeartbeat", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("DroppedUnacknowledgedFacts")
                        .HasColumnType("bigint");

                    b.Property<long>("DroppedUnacknowledgedImages")
                        .HasColumnType("bigint");

                    b.Property<string>("JournalId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("PendingFacts")
                        .HasColumnType("bigint");

                    b.Property<long>("PendingImages")
                        .HasColumnType("bigint");

                    b.Property<bool>("ProtectUnacknowledgedData")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("RejectedFacts")
                        .HasColumnType("bigint");

                    b.Property<long>("RetainedBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceInstanceId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("Key");

                    b.HasIndex("SourceInstanceId", "JournalId")
                        .IsUnique();

                    b.ToTable("FusionJournalHeartbeats", "dbo");
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Infrastructure.Persistence.Fusion.FusionSourceLease", b =>
                {
                    b.Property<string>("SourceInstanceId")
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("JournalId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeaseId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("SourceInstanceId");

                    b.ToTable("FusionSourceLeases", "dbo");
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Infrastructure.Persistence.Management.ManagedDocument", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.ToTable("ManagedDocuments", "dbo");
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Infrastructure.Persistence.Sharding.ParcelLocation", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Suffix")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("SourceKey")
                        .IsUnique()
                        .HasFilter("[SourceKey] IS NOT NULL");

                    b.ToTable("ParcelLocations", "dbo");
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Infrastructure.Persistence.Sharding.ParcelPartitionCatalogEntry", b =>
                {
                    b.Property<string>("Suffix")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("Suffix");

                    b.ToTable("ParcelPartitionCatalog", "dbo");
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Infrastructure.Persistence.Sharding.ParcelProcessingReceipt", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long?>("ParcelId")
                        .HasColumnType("bigint");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Suffix")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Key");

                    b.HasIndex("ParcelId", "RecordedAt");

                    b.ToTable("ParcelProcessingReceipts", "dbo");
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Domain.Aggregates.AuditLogs.WebRequests.WebRequestAuditLogDetail", b =>
                {
                    b.HasOne("Zeye.Sorting.Hub.Domain.Aggregates.AuditLogs.WebRequests.WebRequestAuditLog", "WebRequestAuditLog")
                        .WithOne("Detail")
                        .HasForeignKey("Zeye.Sorting.Hub.Domain.Aggregates.AuditLogs.WebRequests.WebRequestAuditLogDetail", "WebRequestAuditLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebRequestAuditLog");
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.Parcel", b =>
                {
                    b.HasOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.BagInfo", "BagInfo")
                        .WithMany()
                        .HasForeignKey("BagId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsMany("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.ApiRequestInfo", "ApiRequests", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<int>("ApiType")
                                .HasColumnType("int");

                            b1.Property<int>("ElapsedMilliseconds")
                                .HasColumnType("int");

                            b1.Property<string>("Exception")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("nvarchar(2048)");

                            b1.Property<string>("FormattedMessage")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("nvarchar(1024)");

                            b1.Property<string>("Headers")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("nvarchar(2048)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<string>("QueryParams")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("nvarchar(1024)");

                            b1.Property<string>("RawData")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("RequestBody")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("RequestStatus")
                                .HasColumnType("int");

                            b1.Property<DateTime>("RequestTime")
                                .HasColumnType("datetime2");

                            b1.Property<string>("RequestUrl")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)");

                            b1.Property<string>("ResponseBody")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("ResponseTime")
                                .HasColumnType("datetime2");

                            b1.HasKey("Id");

                            b1.HasIndex("ApiType");

                            b1.HasIndex("ParcelId");

                            b1.HasIndex("RequestTime");

                            b1.ToTable("Parcel_ApiRequests", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsMany("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.BarCodeInfo", "BarCodeInfos", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<string>("BarCode")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<int>("BarCodeType")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("CapturedTime")
                                .HasColumnType("datetime2");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint")
                                .HasColumnName("ParcelId");

                            b1.HasKey("Id");

                            b1.HasIndex("CapturedTime");

                            b1.HasIndex("ParcelId");

                            b1.HasIndex("BarCode", "ParcelId");

                            b1.ToTable("Parcel_BarCodeInfos", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.ChuteInfo", "ChuteInfo", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<long?>("ActualChuteId")
                                .HasColumnType("bigint");

                            b1.Property<long?>("BackupChuteId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime>("LandedTime")
                                .HasColumnType("datetime2");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<long?>("TargetChuteId")
                                .HasColumnType("bigint");

                            b1.HasKey("Id");

                            b1.HasIndex("ActualChuteId");

                            b1.HasIndex("ParcelId")
                                .IsUnique();

                            b1.HasIndex("TargetChuteId");

                            b1.ToTable("Parcel_ChuteInfos", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsMany("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.CommandInfo", "CommandInfos", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<int>("ActionType")
                                .HasColumnType("int");

                            b1.Property<string>("CommandPayload")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ConnectionName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<int>("Direction")
                                .HasColumnType("int");

                            b1.Property<string>("FormattedMessage")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("nvarchar(1024)");

                            b1.Property<DateTime>("GeneratedTime")
                                .HasColumnType("datetime2");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<string>("ProtocolName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<int>("ProtocolType")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("ActionType");

                            b1.HasIndex("GeneratedTime");

                            b1.HasIndex("ParcelId");

                            b1.ToTable("Parcel_CommandInfos", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.GrayDetectorInfo", "GrayDetectorInfo", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<string>("AttachBoxInfo")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("nvarchar(2048)");

                            b1.Property<string>("CarrierNumber")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)");

                            b1.Property<string>("CenterPosition")
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)");

                            b1.Property<int>("LinkedCarrierCount")
                                .HasColumnType("int");

                            b1.Property<string>("MainBoxInfo")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("nvarchar(2048)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<string>("RawResult")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("nvarchar(2048)");

                            b1.Property<DateTime>("ResultTime")
                                .HasColumnType("datetime2");

                            b1.HasKey("Id");

                            b1.HasIndex("CarrierNumber");

                            b1.HasIndex("ParcelId")
                                .IsUnique();

                            b1.ToTable("Parcel_GrayDetectorInfos", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsMany("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.ImageInfo", "ImageInfos", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<string>("BucketName")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("CameraName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("CameraSerialNumber")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<int>("CaptureType")
                                .HasColumnType("int");

                            b1.Property<string>("ContentType")
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<string>("CustomName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("ETag")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<int>("ImageType")
                                .HasColumnType("int");

                            b1.Property<string>("ObjectKey")
                                .HasMaxLength(1024)
                                .HasColumnType("nvarchar(1024)");

                            b1.Property<long?>("ObjectSizeBytes")
                                .HasColumnType("bigint");

                            b1.Property<string>("OriginalFileName")
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint")
                                .HasColumnName("ParcelId");

                            b1.Property<string>("RelativePath")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("nvarchar(1024)");

                            b1.Property<string>("Sha256")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<int?>("StorageProvider")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("UploadedAtLocal")
                                .HasColumnType("datetime2")
                                .HasComment("上传完成时间（本地时间）");

                            b1.HasKey("Id");

                            b1.HasIndex("BucketName");

                            b1.HasIndex("ImageType");

                            b1.HasIndex("ParcelId");

                            b1.HasIndex("StorageProvider");

                            b1.HasIndex("UploadedAtLocal");

                            b1.ToTable("Parcel_ImageInfos", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.ParcelDeviceInfo", "DeviceInfo", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<string>("CustomName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("MachineCode")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint")
                                .HasColumnName("ParcelId");

                            b1.Property<string>("WorkstationName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.HasKey("Id");

                            b1.HasIndex("MachineCode");

                            b1.HasIndex("ParcelId")
                                .IsUnique();

                            b1.ToTable("Parcel_DeviceInfos", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.ParcelPositionInfo", "ParcelPositionInfo", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<decimal>("BackgroundX1")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("BackgroundX2")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("BackgroundY1")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("BackgroundY2")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint")
                                .HasColumnName("ParcelId");

                            b1.Property<decimal>("X1")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("X2")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("Y1")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("Y2")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.HasKey("Id");

                            b1.HasIndex("ParcelId")
                                .IsUnique();

                            b1.ToTable("Parcel_PositionInfos", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.SorterCarrierInfo", "SorterCarrierInfo", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<decimal>("ConveyorSpeedWhenLoaded")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<int>("LinkedCarrierCount")
                                .HasColumnType("int");

                            b1.Property<DateTime>("LoadedTime")
                                .HasColumnType("datetime2");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<long>("SorterCarrierId")
                                .HasColumnType("bigint");

                            b1.HasKey("Id");

                            b1.HasIndex("ParcelId")
                                .IsUnique();

                            b1.HasIndex("SorterCarrierId");

                            b1.ToTable("Parcel_SorterCarrierInfos", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.StickingParcelInfo", "StickingParcelInfo", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<int?>("ElapsedMilliseconds")
                                .HasColumnType("int");

                            b1.Property<bool>("IsSticking")
                                .HasColumnType("bit");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint")
                                .HasColumnName("ParcelId");

                            b1.Property<string>("RawData")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("nvarchar(2048)");

                            b1.Property<DateTime?>("ReceiveTime")
                                .HasColumnType("datetime2");

                            b1.HasKey("Id");

                            b1.HasIndex("ParcelId")
                                .IsUnique();

                            b1.ToTable("Parcel_StickingParcelInfos", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsMany("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.VideoInfo", "VideoInfos", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<int>("Channel")
                                .HasColumnType("int");

                            b1.Property<int>("NodeType")
                                .HasColumnType("int");

                            b1.Property<string>("NvrSerialNumber")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint")
                                .HasColumnName("ParcelId");

                            b1.HasKey("Id");

                            b1.HasIndex("NodeType");

                            b1.HasIndex("NvrSerialNumber");

                            b1.HasIndex("ParcelId");

                            b1.ToTable("Parcel_VideoInfos", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsOne("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.VolumeInfo", "VolumeInfo", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<decimal?>("AdjustedHeight")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal?>("AdjustedLength")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal?>("AdjustedVolume")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal?>("AdjustedWidth")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<DateTime?>("BindTime")
                                .HasColumnType("datetime2");

                            b1.Property<string>("EvidenceCode")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<decimal>("FormattedHeight")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("FormattedLength")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("FormattedVolume")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<decimal>("FormattedWidth")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<DateTime>("MeasurementTime")
                                .HasColumnType("datetime2");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<string>("RawVolume")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)");

                            b1.Property<int>("SourceType")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("ParcelId")
                                .IsUnique();

                            b1.ToTable("Parcel_VolumeInfos", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.OwnsMany("Zeye.Sorting.Hub.Domain.Aggregates.Parcels.ValueObjects.WeightInfo", "WeightInfos", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<decimal?>("AdjustedWeight")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<string>("EvidenceCode")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<decimal>("FormattedWeight")
                                .HasPrecision(18, 3)
                                .HasColumnType("decimal(18,3)");

                            b1.Property<long>("ParcelId")
                                .HasColumnType("bigint");

                            b1.Property<string>("RawWeight")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)");

                            b1.Property<DateTime>("WeighingTime")
                                .HasColumnType("datetime2");

                            b1.HasKey("Id");

                            b1.HasIndex("ParcelId");

                            b1.HasIndex("WeighingTime");

                            b1.ToTable("Parcel_WeightInfos", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ParcelId");
                        });

                    b.Navigation("ApiRequests");

                    b.Navigation("BagInfo");

                    b.Navigation("BarCodeInfos");

                    b.Navigation("ChuteInfo");

                    b.Navigation("CommandInfos");

                    b.Navigation("DeviceInfo");

                    b.Navigation("GrayDetectorInfo");

                    b.Navigation("ImageInfos");

                    b.Navigation("ParcelPositionInfo");

                    b.Navigation("SorterCarrierInfo");

                    b.Navigation("StickingParcelInfo");

                    b.Navigation("VideoInfos");

                    b.Navigation("VolumeInfo");

                    b.Navigation("WeightInfos");
                });

            modelBuilder.Entity("Zeye.Sorting.Hub.Domain.Aggregates.AuditLogs.WebRequests.WebRequestAuditLog", b =>
                {
                    b.Navigation("Detail");
                });
#pragma warning restore 612, 618
        }
    }
}
