<Project Sdk="Microsoft.NET.Sdk">

  <!-- 中文说明：共享内核模块的构建与依赖配置。 -->
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Utilities\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="6.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Zeye.Sorting.Hub.Contracts\Zeye.Sorting.Hub.Contracts.csproj" />
  </ItemGroup>

</Project>
