import { retentionPolicyConfigurationKey, retentionPolicyNames } from './configurationModel';

/** 面向配置维护者的中文字段说明；下拉值保留配置原始类型。 */
interface FieldPresentation { label: string; help?: string; unit?: string; min?: number; max?: number; step?: number; choices?: readonly (string | number)[]; choiceLabels?: Readonly<Record<string, string>>; numericPresets?: readonly number[]; listSuggestions?: readonly string[] }
/** 迁移与基线校验共用的失败处理方式。 */
const failureModeChoices = ['Degraded', 'FailFast'];
/** 旧版 Fallback 别名继续对应降级运行。 */
const migrationFailurePresentation = { choices: [...failureModeChoices, 'Fallback'], help: 'Degraded：失败后降级运行；FailFast：失败后停止启动；Fallback：旧版降级方式，等同 Degraded。' };
/** 保留时长和采样比例共用的常用选项，不限制合法自定义值。 */
const retentionDayPresets = [1, 2, 7, 14, 30, 60, 90, 180, 365];
const sampleRatePresets = [0, 0.01, 0.05, 0.1, 0.2, 0.25, 0.5, 0.75, 1];
/** 正文采集上限与连续状态阈值在同类字段间保持一致。 */
const bodyLengthPresets = [0, 1024, 4096, 16384, 65536, 262144, 1048576];
const consecutiveThresholdPresets = [1, 2, 3, 5, 10, 20];
/** 后端以分钟或小时计的后台巡检与治理窗口。 */
const minutePresets = [1, 5, 10, 15, 30, 60, 120, 360, 720, 1440];
const hourPresets = [1, 6, 12, 24, 48, 72, 168, 720, 8760];
/** 备份容量共享常用 GiB 选项，由字段上限过滤。 */
const capacityGiBPresets = [1, 8, 16, 32, 64, 128, 256, 512, 1024];
/** 本地报告的日历选项保留数字值，并显示月份或日期单位。 */
function calendarChoices(count: number, unit: string): Pick<FieldPresentation, 'choices' | 'choiceLabels'> {
  const choices = Array.from({ length: count }, (_, index) => index + 1);
  return { choices, choiceLabels: Object.fromEntries(choices.map(value => [value, `${value} ${unit}`])) };
}
const knownFields: Record<string, FieldPresentation> = {
  'LogCleanup:Enabled': { label: '自动清理日志' },
  'LogCleanup:RetentionDays': { label: '日志保留天数', unit: '天', min: 1, numericPresets: retentionDayPresets, help: '超出保留期的日志由后台巡检清理。' },
  'LogCleanup:CheckIntervalHours': { label: '日志巡检间隔', unit: '小时', min: 1, numericPresets: [1, 2, 6, 12, 24, 48, 72, 168] },
  'LogCleanup:LogDirectory': { label: '日志目录', help: '可使用绝对路径或相对程序目录的路径。' },
  'ResourceThresholds:MaxConnectionPoolSize': { label: '连接池告警阈值', min: 1, max: 10000, numericPresets: [32, 64, 100, 128, 200, 256, 512], help: '用于启动基线审计；实际连接池大小通过数据库连接字符串设置。' },
  'ResourceThresholds:MemoryWarningThresholdMB': { label: '内存告警阈值', unit: 'MB', min: 0, max: 1048576, numericPresets: [0, 256, 512, 1024, 2048, 4096, 8192], help: '设为 0 关闭此项告警。' },
  'ResourceThresholds:HandleWarningThreshold': { label: '句柄告警阈值', min: 0, max: 1000000, numericPresets: [0, 1000, 5000, 10000, 50000, 100000], help: '设为 0 关闭此项告警。' },
  'ResourceThresholds:MinimumDiskFreeMB': { label: '最小磁盘剩余空间', unit: 'MB', min: 0, max: 1048576, numericPresets: [0, 512, 1024, 2048, 5120, 10240], help: '设为 0 关闭此项告警。' },
  'ResourceThresholds:SampleIntervalSeconds': { label: '资源采样间隔', unit: '秒', min: 10, max: 3600, numericPresets: [10, 30, 60, 120, 300, 600, 1800, 3600] },
  'WebRequestAuditLog:Enabled': { label: '记录请求审计' },
  'WebRequestAuditLog:SampleRate': { label: '成功请求采样率', min: 0, max: 1, step: 0.01, numericPresets: sampleRatePresets, help: '0～1；0.1 表示采集约 10% 的常规成功请求。' },
  'WebRequestAuditLog:AlwaysAuditFailedRequests': { label: '始终记录失败请求' },
  'WebRequestAuditLog:SlowRequestThresholdMs': { label: '慢请求阈值', unit: '毫秒', min: 0, numericPresets: [0, 100, 500, 1000, 2000, 5000, 10000], help: '设为 0 关闭慢请求强制审计。' },
  'WebRequestAuditLog:ExcludedPathPrefixes': { label: '排除的请求路径', listSuggestions: ['/health', '/swagger', '/favicon.ico'], help: '逐项选择或添加自定义路径前缀；移除所有项可清空排除列表。' },
  'WebRequestAuditLog:IncludeRequestBody': { label: '记录请求正文' },
  'WebRequestAuditLog:IncludeResponseBody': { label: '记录响应正文' },
  'WebRequestAuditLog:MaxRequestBodyLength': { label: '请求正文采集上限', unit: '字符', min: 0, max: 1048576, numericPresets: bodyLengthPresets },
  'WebRequestAuditLog:MaxResponseBodyLength': { label: '响应正文采集上限', unit: '字符', min: 0, max: 1048576, numericPresets: bodyLengthPresets },
  'WebRequestAuditLog:BackgroundQueueCapacity': { label: '审计队列容量', min: 1, max: 1048576, numericPresets: [256, 1024, 4096, 16384, 65536] },
  'WebRequestAuditLog:BackgroundBatchSize': { label: '审计写入批量', min: 1, max: 10000, numericPresets: [50, 100, 200, 500, 1000, 5000] },
  'WebRequestAuditLog:BackgroundBatchDelayMs': { label: '批量合并等待', unit: '毫秒', min: 0, max: 60000, numericPresets: [0, 50, 100, 200, 500, 1000, 5000] },
  'WebRequestAuditLog:DropLogIntervalSeconds': { label: '队列丢弃告警间隔', unit: '秒', min: 1, max: 3600, numericPresets: [10, 30, 60, 300, 600, 3600] },
  'Access:EnforceAuthorization': { label: '启用访问授权', help: '启用后，业务页面和接口需要登录或合法的机器凭据。' },
  'Access:BootstrapKey': { label: '管理员初始化密钥' },
  'Access:MachineApiKey': { label: '机器接口密钥' },
  'AuditReadOnlyApi:Enabled': { label: '启用审计查询接口' },
  'AuditReadOnlyApi:RequireAuthorization': { label: '审计查询要求授权' },
  'Hosting:Urls': { label: '服务监听地址', help: '修改后在下次启动时生效，例如 http://0.0.0.0:5078。' },
  'Hosting:EnableHttpsRedirection': { label: '启用 HTTPS 重定向' },
  'Persistence:Provider': { label: '业务数据库', choices: ['MySql', 'SqlServer', 'Oracle', 'SQLite'], help: '业务与历史数据存入所选数据库。切换数据库需要重启，并迁移已有业务数据。' },
  'Persistence:Migration:FailureStrategy': { label: '统一迁移失败处理', ...migrationFailurePresentation },
  'Persistence:Migration:FailureStrategy:Production': { label: '生产环境迁移失败处理', ...migrationFailurePresentation },
  'Persistence:Migration:FailureStrategy:NonProduction': { label: '非生产环境迁移失败处理', ...migrationFailurePresentation },
  'Persistence:BaselineData:FailureMode': { label: '基线校验失败处理', choices: failureModeChoices, help: 'Degraded：校验失败后降级运行；FailFast：校验失败后停止启动。' },
  'Persistence:Backup:PollIntervalMinutes': { label: '备份治理巡检间隔', min: 1, max: 1440, unit: '分钟', numericPresets: minutePresets },
  'Persistence:Backup:MaxAllowedBackupAgeHours': { label: '备份最长允许年龄', min: 1, max: 8760, unit: '小时', numericPresets: hourPresets },
  'Persistence:Backup:OperationTimeoutMinutes': { label: '备份与恢复执行预算', min: 1, max: 1440, unit: '分钟', numericPresets: minutePresets },
  'Persistence:Backup:MaxExportGiB': { label: '单次备份导出容量上限', min: 1, max: 1024, unit: 'GiB', numericPresets: capacityGiBPresets },
  'Persistence:Backup:ArtifactRetentionDays': { label: '完整备份保留天数', min: 1, max: 3650, unit: '天', numericPresets: retentionDayPresets },
  'Persistence:Backup:MinimumRetainedArtifacts': { label: '最低安全备份份数', min: 2, max: 100, numericPresets: [2, 3, 5, 7, 10, 20, 30, 50, 100], help: '2～100 份，且不能大于完整备份最多保留份数。' },
  'Persistence:Backup:MaxRetainedArtifacts': { label: '完整备份最多保留份数', min: 2, max: 5000, numericPresets: [7, 24, 168, 744, 1000, 2000, 5000], help: '不能小于最低安全备份份数，最大 5000 份。' },
  'Persistence:Backup:MaxRetainedGiB': { label: '完整备份目录容量上限', min: 1, max: 4096, unit: 'GiB', numericPresets: [...capacityGiBPresets, 2048, 4096] },
  'Persistence:ReadOnlyDatabase:MaxReportTimeRangeDays': { label: '报表最大查询范围', min: 1, max: 366, unit: '天', numericPresets: [1, 7, 14, 30, 31, 90, 180, 365, 366] },
  'Persistence:ReadOnlyDatabase:MaxReportRows': { label: '报表最大返回行数', min: 1, max: 100000, numericPresets: [100, 500, 1000, 5000, 10000, 50000, 100000] },
  'Persistence:Sharding:Prebuild:PrebuildAheadHours': { label: '分表预建窗口', min: 1, max: 8760, unit: '小时', numericPresets: hourPresets },
  'Persistence:Sharding:Strategy:Volume:FinerGranularity:BucketCount': { label: '日内细分桶数量', min: 2, max: 128, numericPresets: [2, 4, 8, 16, 32, 64, 128], help: '2～128；仅日内按桶细分模式使用，其他合法桶数量可通过自定义设置。' },
  'ObjectStorage:Provider': { label: '对象存储提供程序', choices: ['Minio'], help: '当前支持 MinIO 对象存储。' },
  'Persistence:AutoTuning:MonthlyReportDay': { label: '每月巡检报告生成日期', ...calendarChoices(28, '日'), help: '每月在所选日期按日报生成时间输出月报；支持 1～28 日，避免二月日期越界。' },
  'Persistence:AutoTuning:AnnualDashboardMonth': { label: '年度看板生成月份', ...calendarChoices(12, '月'), help: '在所选月份的 1 日，按日报生成时间输出年度看板。' },
  [retentionPolicyConfigurationKey]: { label: '数据保留策略', help: '选择保留对象并设置保留天数（1～3650 天）；空列表表示不配置保留策略。' },
  [`${retentionPolicyConfigurationKey}:Name`]: { label: '保留对象', choices: retentionPolicyNames, choiceLabels: { WebRequestAuditLog: '请求审计记录', InboxMessage: '接入消息', IdempotencyRecord: '幂等记录', ArchiveTask: '归档任务', DeadLetterWriteEntry: '写入失败记录', SlowQueryProfile: '慢查询画像' } },
  [`${retentionPolicyConfigurationKey}:RetentionDays`]: { label: '保留天数', min: 1, max: 3650, numericPresets: retentionDayPresets, unit: '天' },
  'Persistence:Diagnostics:WarmupConnectionCount': { label: '预热连接数', min: 1, max: 64, numericPresets: [1, 2, 4, 8, 16, 32, 64] },
  'Persistence:Diagnostics:FailureThreshold': { label: '连续失败次数阈值', min: 1, max: 20, numericPresets: consecutiveThresholdPresets },
  'Persistence:Diagnostics:RecoveryThreshold': { label: '连续恢复次数阈值', min: 1, max: 20, numericPresets: consecutiveThresholdPresets },
  'Persistence:WriteBuffering:MaxRetryCount': { label: '最大重试次数', min: 0, max: 10, choices: Array.from({ length: 11 }, (_, index) => index) },
  'Persistence:Sharding:ParcelStartTime': { label: '包裹分表起始时间', help: '选择本地日期和时间，不附加时区偏移。' },
  'Persistence:AutoTuning:DailyReportLocalTime': { label: '日报生成时间', help: '选择本地时间，格式为 HH:mm:ss。' },
  'Persistence:AutoTuning:Autonomous:Execution:PeakStartLocalTime': { label: '高峰开始时间', help: '使用本地时间；与结束时间共同确定高峰执行窗口。' },
  'Persistence:AutoTuning:Autonomous:Execution:PeakEndLocalTime': { label: '高峰结束时间', help: '使用本地时间；支持跨午夜的高峰窗口。' },
  'Persistence:AutoTuning:Autonomous:Validation:PlanProbe:SampleRate': { label: '执行计划探测采样率', min: 0, max: 1, step: 0.01, numericPresets: sampleRatePresets },
  'Persistence:AutoTuning:Autonomous:Execution:WhitelistedTables': { label: '允许自动调优的表', listSuggestions: ['parcels', 'dbo.parcels', 'webrequestauditlogs', 'dbo.webrequestauditlogs', 'webrequestauditlogdetails', 'dbo.webrequestauditlogdetails'], help: '逐项选择或添加实际表名，支持 table 或 schema.table；空列表会阻断全部表的自动动作。' },
  'Persistence:Sharding:HashSharding:ExpansionPlan:Stages': { label: '扩容步骤', listSuggestions: ['warmup', 'dual-write', 'verification', 'cutover'], help: '按顺序选择或添加阶段；可上移、下移调整顺序，保留自定义阶段。' },
  'Persistence:Sharding:Strategy:Mode': { label: '策略模式', choices: ['Time', 'Volume', 'Hybrid'], help: 'Time：按时间；Volume：按数据量；Hybrid：组合策略。' },
  'Persistence:Sharding:Strategy:Time:Granularity': { label: '时间分表粒度', choices: ['PerMonth', 'PerWeek', 'PerDay'], help: 'PerMonth：按月；PerWeek：按周；PerDay：按天。' },
  'Persistence:Sharding:Strategy:Volume:ActionOnThreshold': { label: '达到阈值后的操作', choices: ['AlertOnly', 'SwitchToPerDay'], help: 'AlertOnly：仅告警；SwitchToPerDay：切换到按天分表决策。' },
  'Persistence:Sharding:Strategy:Volume:FinerGranularity:ModeWhenPerDayStillHot': { label: '按天分表仍过热时的策略', choices: ['PerHour', 'BucketedPerDay', 'None'], help: 'PerHour：按小时细分；BucketedPerDay：日内按桶细分；None：不继续细分。日内按桶细分时需要设置桶数量，当前用于扩展规划。' },
  'Persistence:Sharding:Strategy:Volume:FinerGranularity:Lifecycle': { label: '分表生命周期', choices: ['PlanOnly', 'AlertOnly', 'FutureExecutable'], help: 'PlanOnly：仅规划；AlertOnly：仅告警；FutureExecutable：预留未来受控执行。当前不会直接执行细分迁移。' },
  'Persistence:MySql:ServerVersion': { label: 'MySQL 服务版本', help: '填写明确版本，避免启动时自动探测。' },
  'ConnectionStrings:MySql': { label: 'MySQL 连接字符串' },
  'ConnectionStrings:MySqlReadOnly': { label: 'MySQL 只读连接字符串' },
  'ConnectionStrings:SqlServer': { label: 'SQL Server 连接字符串' },
  'ConnectionStrings:SqlServerReadOnly': { label: 'SQL Server 只读连接字符串' },
  'ConnectionStrings:Oracle': { label: 'Oracle 业务连接字符串', help: '填写目标 PDB 服务与业务用户。' },
  'ConnectionStrings:OracleAdministration': { label: 'Oracle 初始化管理连接', help: '首次自动创建业务用户时使用目标 PDB 的管理连接。' },
  'ConnectionStrings:OracleReadOnly': { label: 'Oracle 只读连接字符串' },
  'ConnectionStrings:SQLite': { label: 'SQLite 业务文件', help: '使用 Data Source=文件路径；相对路径以服务内容目录为基准，首次启动自动建立目录与文件。' },
  'ConnectionStrings:SQLiteReadOnly': { label: 'SQLite 只读连接字符串', help: '只读连接应填写 Mode=ReadOnly。' },
};
const labels: Record<string, string> = {
  Hosting: '服务运行', Swagger: '接口文档', BrowserAutoOpen: '启动浏览器',
  WebRequestAuditLog: '请求审计', AuditReadOnlyApi: '审计查询', LogCleanup: '日志清理',
  ResourceThresholds: '资源阈值', Logging: '应用日志过滤', LogLevel: '最低日志级别', Access: '访问保护',
  ConnectionStrings: '数据库连接字符串', Persistence: '数据库', ObjectStorage: '对象存储', Minio: 'MinIO',
  Backup: '备份治理', DataRetention: '数据保留', Retention: '数据保留', Archive: '数据归档', Archiving: '数据归档', Migration: '启动迁移', MigrationGovernance: '迁移治理',
  BaselineData: '基线数据', ReadOnlyDatabase: '只读副本', ConnectionWarmup: '连接预热',
  Sharding: '分表', ShardingPrebuild: '分表预建', ShardingRuntimeInspection: '分表巡检', AutoTuning: '自动调优',
  Enabled: '启用', IsEnabled: '启用', DryRun: '预演模式', Endpoint: '访问端点', UseSsl: '使用 HTTPS',
  AccessKey: '访问密钥', SecretKey: '私有密钥', Region: '区域', Provider: '提供程序',
  PollIntervalMinutes: '巡检间隔（分钟）', RetentionDays: '保留天数', PrebuildAheadHours: '预建窗口（小时）',
  BackupDirectory: '备份目录', MaxAllowedBackupAgeHours: '备份最长允许年龄（小时）',
  DatabaseBootstrap: '数据库初始化', EnsureDatabaseExists: '自动创建数据库', Bootstrap: '启动自检',
  Isolator: '操作隔离保护', EnableGuard: '启用操作保护', AllowDangerousActionExecution: '允许执行危险操作',
  WriteBuffering: '写入缓冲', PerformanceTuning: '性能参数', SqlLogging: '查询日志', Diagnostics: '连接诊断',
  RepositoryDangerousActions: '仓储危险操作', ParcelRemoveExpired: '清理过期包裹',
  Strategy: '分表策略', Time: '按时间分表', Volume: '按数据量分表', Observation: '容量观测',
  FinerGranularity: '更细分表策略', HashSharding: '哈希分表', ExpansionPlan: '扩容计划',
  Governance: '分表治理', RuntimeInspection: '运行巡检', Prebuild: '分表预建', WriteRouting: '写入路由',
  FailureStrategy: '迁移失败处理', Autonomous: '自主调优', Policy: '执行策略', Execution: '执行控制',
  Validation: '效果验证', SevereRollback: '严重退化回滚', PlanProbe: '执行计划探测', CapacityPrediction: '容量预测',
  SlowQueryProfile: '慢查询画像', QueryGovernance: '查询治理', ConnectionPool: '连接池',
  MySql: 'MySQL', SqlServer: 'SQL Server', Oracle: 'Oracle', SQLite: 'SQLite', Sqlite: 'SQLite',
  Default: '默认', 'Microsoft.Hosting.Lifetime': '服务生命周期', 'Microsoft.EntityFrameworkCore': 'EF Core',
  'Microsoft.AspNetCore': 'ASP.NET Core',
  AllowedHosts: '允许的主机名', Urls: '服务监听地址', Url: '打开地址', RoutePrefix: '文档路由前缀',
  DocumentTitle: '文档标题', DocumentName: '文档名称', JsonEndpoint: '文档接口地址',
  Production: '生产环境', NonProduction: '非生产环境', FailStartupOnError: '迁移失败时阻止启动',
  ArchiveDirectory: '归档目录', BlockDangerousMigrationInProduction: '阻止生产环境中的危险迁移',
  IsValidationEnabled: '启用基线校验', IsSeedEnabled: '启用初始数据写入', FailureMode: '校验失败处理方式',
  BackupFilePrefix: '备份文件名前缀', RestoreRunbookDirectory: '恢复操作手册目录', DrillRecordDirectory: '恢复演练记录目录',
  OperationTimeoutMinutes: '操作超时时间（分钟）', MaxExportGiB: '单次导出容量上限（GiB）',
  ArtifactRetentionEnabled: '自动清理过期备份', ArtifactRetentionDays: '备份保留天数',
  MinimumRetainedArtifacts: '最低保留备份份数', MaxRetainedArtifacts: '最多保留备份份数', MaxRetainedGiB: '备份保留容量上限（GiB）',
  FallbackToPrimaryWhenUnavailable: '只读副本不可用时回退主库',
  MaxReportTimeRangeDays: '报表查询最大时间范围（天）', MaxReportRows: '报表最大返回行数',
  BatchSize: '单批处理条数', Policies: '数据保留策略',
  CreateShardingTableOnStarting: '启动时创建分表', AllowTableCreation: '允许创建分表',
  ParcelStartTime: '包裹分表起始时间', ParcelRelatedHashShardingMod: '包裹关联数据哈希分片数',
  Mode: '策略模式', Granularity: '时间分表粒度', MaxRowsPerShard: '每个分表最大行数',
  HotThresholdRatio: '热点阈值比例', Source: '观测数据来源', EstimatedRowsPerShard: '每个分表预估行数',
  ObservedHotRatio: '观测热点比例', CurrentEstimatedRowsPerShard: '当前每个分表预估行数', CurrentObservedHotRatio: '当前观测热点比例',
  ActionOnThreshold: '达到阈值后的操作', ModeWhenPerDayStillHot: '按天分表仍过热时的策略',
  Lifecycle: '分表生命周期', RequirePrebuildGuard: '要求预建保护', ExpansionTriggerRatio: '扩容触发比例',
  CurrentMod: '当前哈希分片数', TargetMod: '目标哈希分片数', Stages: '扩容步骤',
  PrebuildWindowHours: '预建时间窗口（小时）', EnablePerDayGuard: '启用按天分表保护',
  KeepRecentShardCount: '保留最近分表数量', Runbook: '运维操作手册', InspectionIntervalMinutes: '巡检间隔（分钟）',
  ShouldCheckIndexes: '检查分表索引', ShouldCheckNextPeriodTables: '检查下一周期分表', ShouldCheckCapacity: '检查分表容量',
  CommandTimeoutSeconds: '数据库命令超时时间（秒）', DbContextPoolSize: '数据上下文池容量',
  MinCommandElapsedMilliseconds: '查询耗时记录阈值（毫秒）', MaxRetryCount: '最大重试次数',
  MaxRetryDelaySeconds: '最大重试延迟（秒）', EnableQuerySqlLogging: '记录查询语句',
  IsWarmupEnabled: '启用连接预热', WarmupConnectionCount: '预热连接数',
  ProbeTimeoutMilliseconds: '探测超时时间（毫秒）', ProbeCacheMilliseconds: '探测结果缓存时间（毫秒）',
  FailureThreshold: '连续失败次数阈值', RecoveryThreshold: '连续恢复次数阈值',
  ChannelCapacity: '写入队列容量', FlushIntervalMilliseconds: '批量写入间隔（毫秒）',
  RetryBaseDelayMilliseconds: '重试基础延迟（毫秒）', MaxRetryDelayMilliseconds: '最大重试延迟（毫秒）',
  RetryJitterMilliseconds: '重试随机延迟（毫秒）', BackpressureRejectThreshold: '队列积压拒绝阈值',
  DeadLetterCapacity: '失败记录队列容量', ShutdownDrainTimeoutSeconds: '停机等待队列写完的超时时间（秒）',
  WorkerPollIntervalSeconds: '归档任务轮询间隔（秒）', SampleItemLimit: '归档预览样本上限',
  ExecutionTimeoutSeconds: '执行超时时间（秒）', AbandonedTaskTimeoutMinutes: '停滞任务判定超时（分钟）',
  MaxAutomaticRecoveryAttempts: '最大自动恢复次数', AutomaticRecoveryBatchSize: '自动恢复批次大小',
  SlowQueryThresholdMilliseconds: '慢查询耗时阈值（毫秒）', AnalysisBatchSize: '分析批次大小',
  TriggerCount: '调优触发次数', MaxActionsPerCycle: '每轮调优操作上限', MaxQueueSize: '调优队列容量',
  AnalyzeIntervalSeconds: '分析间隔（秒）', AggregationTopN: '聚合排名数量', WindowMinutes: '统计窗口（分钟）',
  TopN: '排名数量', MaxFingerprintCount: '查询指纹数量上限', MaxSampleCountPerFingerprint: '每个查询指纹的样本上限',
  ReportIntervalHours: '报告生成间隔（小时）', RecommendationP99Milliseconds: '索引建议耗时阈值（P99，毫秒）',
  MinimumCallCount: '最低调用次数', AlertDebounceMinCallCount: '告警判定最低调用次数',
  AlertP99Milliseconds: '查询耗时告警阈值（P99，毫秒）', AlertTimeoutRatePercent: '超时率告警阈值（%）',
  AlertDeadlockCount: '死锁次数告警阈值', AlertDebounceWindowSeconds: '告警防抖窗口（秒）',
  AlertConsecutiveWindows: '触发告警所需连续窗口数', AlertRecoveryConsecutiveWindows: '解除告警所需连续窗口数',
  DailyReportLocalTime: '日报生成时间（本地时间）', MonthlyReportDay: '月报生成日期', MonthlyReportArchivePath: '月报归档路径',
  AnnualDashboardMonth: '年度看板生成月份', AnnualDashboardArchivePath: '年度看板归档路径',
  ShardingGovernanceHitRateThreshold: '分表治理命中率阈值', BaselineCommandTimeoutSeconds: '基准命令超时时间（秒）',
  BaselineMaxRetryCount: '基准最大重试次数', BaselineMaxRetryDelaySeconds: '基准最大重试延迟（秒）',
  EnableFullAutomation: '启用全自动调优', MinTableHeatCalls: '最低表访问次数', MaxRiskScore: '风险评分上限',
  PeakMaxRiskScore: '高峰期风险评分上限', PeakMaxTableHeatCalls: '高峰期表访问次数上限',
  MaxExecuteActionsPerCycle: '每轮实际执行操作上限', ActionExecutionTimeoutSeconds: '单次操作执行超时（秒）',
  SkipExecutionDuringPeak: '高峰期跳过执行', PeakStartLocalTime: '高峰期开始时间（本地时间）', PeakEndLocalTime: '高峰期结束时间（本地时间）',
  WhitelistedTables: '允许自动调优的表', GradualSwitchDryRunCycles: '切换真实执行前的预演轮数',
  EnableAutoValidation: '启用自动效果验证', EnableAutoRollback: '启用自动回滚', DelayCycles: '验证等待轮数',
  P95IncreasePercent: '响应耗时增幅阈值（P95，%）', P99IncreasePercent: '响应耗时增幅阈值（P99，%）',
  ErrorRateIncreasePercent: '错误率增幅阈值（%）', TimeoutRateIncreasePercent: '超时率增幅阈值（%）',
  DeadlockIncreaseCount: '死锁增加次数阈值', PauseActionCyclesOnRegression: '性能退化后暂停轮数',
  Enable: '启用', SampleRate: '采样率', EnableCapacityPrediction: '启用容量预测', ProjectionDays: '容量预测天数',
  GrowthAlertRows: '数据增长告警行数', HotLayeringRows: '冷热分层触发行数',
  ParcelImagesBucket: '包裹图片存储桶', GenericFilesBucket: '通用文件存储桶',
  PresignedUploadExpireSeconds: '上传签名有效期（秒）', PresignedReadExpireSeconds: '读取签名有效期（秒）',
  PresignedUploadExpiresSeconds: '上传签名有效期（秒）', PresignedReadExpiresSeconds: '读取签名有效期（秒）',
  MultipartPartExpireSeconds: '分片上传签名有效期（秒）', EnsureBucketsExist: '自动创建存储桶',
};
/** 优先使用完整路径说明，其余已知字段使用中文名称，扩展字段保留原名。 */
export function configurationFieldPresentation(key: string): FieldPresentation {
  if (key.toLowerCase().startsWith('logging:loglevel:')) return { label: `${labels[key.split(':').at(-1)!] ?? key.split(':').at(-1)} 日志级别`, choices: ['Trace', 'Debug', 'Information', 'Warning', 'Error', 'Critical', 'None'], help: '应用日志过滤；NLog 文件目标与自身规则仍由日志配置文件维护。' };
  const known = Object.entries(knownFields).find(([path]) => path.toLowerCase() === key.toLowerCase());
  return known?.[1] ?? { label: labels[key.split(':').at(-1)!] ?? key.split(':').at(-1)! };
}
/** 分组标题复用字段中文名称，产品名称和扩展分组保留原名。 */
export function configurationGroupLabel(path: string[]): string { return path.map(part => labels[part] ?? part).join(' / '); }
