<Project Sdk="Microsoft.NET.Sdk">

  <!-- 中文说明：应用层模块的构建与依赖配置。 -->
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="6.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Zeye.Sorting.Hub.Contracts\Zeye.Sorting.Hub.Contracts.csproj" />
    <ProjectReference Include="..\Zeye.Sorting.Hub.Domain\Zeye.Sorting.Hub.Domain.csproj" />
    <ProjectReference Include="..\Zeye.Sorting.Hub.SharedKernel\Zeye.Sorting.Hub.SharedKernel.csproj" />
  </ItemGroup>

</Project>
