// Generated by qa/extract_header_brand_assets.py from the supplied references.
export const headerBrandAssets = {
  "P01": {
    "file": "header-brand-P01.png",
    "source": "P01-workbench.png",
    "crop": [
      25,
      14,
      221,
      42
    ],
    "x": 25,
    "y": 14,
    "width": 196,
    "height": 28
  },
  "P02": {
    "file": "header-brand-P02.png",
    "source": "P02-parcel-list.png",
    "crop": [
      25,
      14,
      220,
      42
    ],
    "x": 25,
    "y": 14,
    "width": 195,
    "height": 28
  },
  "P03": {
    "file": "header-brand-P03.png",
    "source": "P03-parcel-detail.png",
    "crop": [
      26,
      14,
      233,
      44
    ],
    "x": 26,
    "y": 14,
    "width": 207,
    "height": 30
  },
  "P04": {
    "file": "header-brand-P04.png",
    "source": "P04-parcel-create.png",
    "crop": [
      25,
      14,
      221,
      42
    ],
    "x": 25,
    "y": 14,
    "width": 196,
    "height": 28
  },
  "P05": {
    "file": "header-brand-P05.png",
    "source": "P05-parcel-batch.png",
    "crop": [
      25,
      14,
      221,
      42
    ],
    "x": 25,
    "y": 14,
    "width": 196,
    "height": 28
  },
  "P06": {
    "file": "header-brand-P06.png",
    "source": "P06-expired-cleanup.png",
    "crop": [
      25,
      14,
      221,
      43
    ],
    "x": 25,
    "y": 14,
    "width": 196,
    "height": 29
  },
  "P07": {
    "file": "header-brand-P07.png",
    "source": "P07-request-audit-list.png",
    "crop": [
      25,
      14,
      221,
      42
    ],
    "x": 25,
    "y": 14,
    "width": 196,
    "height": 28
  },
  "P08": {
    "file": "header-brand-P08.png",
    "source": "P08-request-audit-detail.png",
    "crop": [
      25,
      14,
      221,
      42
    ],
    "x": 25,
    "y": 14,
    "width": 196,
    "height": 28
  },
  "P09": {
    "file": "header-brand-P09.png",
    "source": "P09-slow-query-list.png",
    "crop": [
      26,
      15,
      235,
      45
    ],
    "x": 26,
    "y": 15,
    "width": 209,
    "height": 30
  },
  "P10": {
    "file": "header-brand-P10.png",
    "source": "P10-slow-query-detail.png",
    "crop": [
      25,
      14,
      220,
      42
    ],
    "x": 25,
    "y": 14,
    "width": 195,
    "height": 28
  },
  "P11": {
    "file": "header-brand-P11.png",
    "source": "P11-archive-tasks.png",
    "crop": [
      25,
      13,
      225,
      42
    ],
    "x": 25,
    "y": 13,
    "width": 200,
    "height": 29
  },
  "P13": {
    "file": "header-brand-P13.png",
    "source": "P13-health-check.png",
    "crop": [
      26,
      15,
      234,
      45
    ],
    "x": 26,
    "y": 15,
    "width": 208,
    "height": 30
  },
  "P14": {
    "file": "header-brand-P14.png",
    "source": "P14-help.png",
    "crop": [
      26,
      12,
      219,
      40
    ],
    "x": 26,
    "y": 12,
    "width": 193,
    "height": 28
  },
  "P15b": {
    "file": "header-brand-P15b.png",
    "source": "P15b-users-roles.png",
    "crop": [
      25,
      14,
      221,
      42
    ],
    "x": 25,
    "y": 14,
    "width": 196,
    "height": 28
  },
  "P16": {
    "file": "header-brand-P16.png",
    "source": "P16-live-operations.png",
    "crop": [
      25,
      14,
      220,
      42
    ],
    "x": 25,
    "y": 14,
    "width": 195,
    "height": 28
  },
  "P17": {
    "file": "header-brand-P17.png",
    "source": "P17-rules.png",
    "crop": [
      25,
      14,
      221,
      43
    ],
    "x": 25,
    "y": 14,
    "width": 196,
    "height": 29
  },
  "P18": {
    "file": "header-brand-P18.png",
    "source": "P18-analytics.png",
    "crop": [
      25,
      13,
      220,
      41
    ],
    "x": 25,
    "y": 13,
    "width": 195,
    "height": 28
  },
  "P19": {
    "file": "header-brand-P19.png",
    "source": "P19-backup-recovery.png",
    "crop": [
      27,
      14,
      235,
      45
    ],
    "x": 27,
    "y": 14,
    "width": 208,
    "height": 31
  },
  "P20": {
    "file": "header-brand-P20.png",
    "source": "P20-partition-management.png",
    "crop": [
      27,
      15,
      234,
      45
    ],
    "x": 27,
    "y": 15,
    "width": 207,
    "height": 30
  },
  "P21": {
    "file": "header-brand-P21.png",
    "source": "P21-settings.png",
    "crop": [
      25,
      14,
      220,
      42
    ],
    "x": 25,
    "y": 14,
    "width": 195,
    "height": 28
  }
} as const;

export type HeaderBrandKey = keyof typeof headerBrandAssets;
