using System.Security.Cryptography;
using System.Text.Json;
using Zeye.Sorting.Hub.Contracts.Models.Parcels.Processing;
using Zeye.Sorting.Hub.Domain.Aggregates.Parcels.Processing;
using Zeye.Sorting.Hub.Domain.Enums.Parcels;

namespace Zeye.Sorting.Hub.Application.Services.Parcels;

/// <summary>处理记录合同与领域事实的集中映射。</summary>
public static class ParcelProcessingContractMapper {
    /// <summary>验证来源事实并设置服务端入库时间与原始合同内容哈希。</summary>
    public static ParcelProcessingRecord ToDomain(ParcelProcessingRecordRequest request, DateTime recordedAt) {
        var record = new ParcelProcessingRecord {
            PreviousCreationGapMilliseconds = request.PreviousCreationGapMilliseconds,
            IsSpacingViolation = request.IsSpacingViolation,
            IsAwaitingWcsDecision = request.IsAwaitingWcsDecision,
            WorkstationName = request.WorkstationName,
            RecordId = request.RecordId,
            SourceInstanceId = request.SourceInstanceId,
            SourceRunId = request.SourceRunId,
            SourceParcelId = request.SourceParcelId,
            Stage = (ParcelProcessingStage)request.Stage,
            OccurredAt = request.OccurredAt,
            IsSuccess = request.IsSuccess,
            AttemptNumber = request.AttemptNumber,
            Barcode = request.Barcode,
            BarcodesJson = request.BarcodesJson,
            WeightGrams = request.WeightGrams,
            LengthMm = request.LengthMm,
            WidthMm = request.WidthMm,
            HeightMm = request.HeightMm,
            VolumeMm3 = request.VolumeMm3,
            VolumetricWeightGrams = request.VolumetricWeightGrams,
            ReceivedAt = request.ReceivedAt,
            MeasuredAt = request.MeasuredAt,
            HasReliableTimestamp = request.HasReliableTimestamp,
            HasReliableFrameBoundary = request.HasReliableFrameBoundary,
            CorrelationId = request.CorrelationId,
            TriggerBatch = request.TriggerBatch,
            ScanSequence = request.ScanSequence,
            MessageIdentity = request.MessageIdentity,
            BindingMode = request.BindingMode,
            CandidateSourceParcelId = request.CandidateSourceParcelId,
            FinalSourceParcelId = request.FinalSourceParcelId,
            DeltaMilliseconds = request.DeltaMilliseconds,
            DecisionReason = request.DecisionReason,
            FifoRecoveryMode = request.FifoRecoveryMode,
            Provider = request.Provider,
            TaskCode = request.TaskCode,
            TargetChuteCode = request.TargetChuteCode,
            DispatchedChuteCode = request.DispatchedChuteCode,
            ActualChuteCode = request.ActualChuteCode,
            IsFallback = request.IsFallback,
            IsRoutingBlocked = request.IsRoutingBlocked,
            ExceptionCode = request.ExceptionCode,
            ErrorMessage = request.ErrorMessage,
            RawPayload = request.RawPayload,
            RequestUrl = request.RequestUrl,
            RequestHeaders = request.RequestHeaders,
            RequestBody = request.RequestBody,
            ResponseBody = request.ResponseBody,
            ResponseStatusCode = request.ResponseStatusCode,
            RequestAt = request.RequestAt,
            ResponseAt = request.ResponseAt,
            ElapsedMilliseconds = request.ElapsedMilliseconds,
            ImagePath = request.ImagePath,
            ImageCamera = request.ImageCamera,
            ImageContentHash = request.ImageContentHash,
            RecordedAt = recordedAt,
            PartitionTime = recordedAt,
            PayloadHash = Convert.ToHexString(SHA256.HashData(JsonSerializer.SerializeToUtf8Bytes(request)))
        };
        record.Validate();
        return record;
    }

    /// <summary>返回原始来源事实及持久化定位信息。</summary>
    public static ParcelProcessingRecordResponse ToResponse(ParcelProcessingRecord record) => new() {
        PreviousCreationGapMilliseconds = record.PreviousCreationGapMilliseconds,
        IsSpacingViolation = record.IsSpacingViolation,
        IsAwaitingWcsDecision = record.IsAwaitingWcsDecision,
        WorkstationName = record.WorkstationName,
        RecordId = record.RecordId,
        SourceInstanceId = record.SourceInstanceId,
        SourceRunId = record.SourceRunId,
        SourceParcelId = record.SourceParcelId,
        Stage = (int)record.Stage,
        OccurredAt = record.OccurredAt,
        IsSuccess = record.IsSuccess,
        AttemptNumber = record.AttemptNumber,
        Barcode = record.Barcode,
        BarcodesJson = record.BarcodesJson,
        WeightGrams = record.WeightGrams,
        LengthMm = record.LengthMm,
        WidthMm = record.WidthMm,
        HeightMm = record.HeightMm,
        VolumeMm3 = record.VolumeMm3,
        VolumetricWeightGrams = record.VolumetricWeightGrams,
        ReceivedAt = record.ReceivedAt,
        MeasuredAt = record.MeasuredAt,
        HasReliableTimestamp = record.HasReliableTimestamp,
        HasReliableFrameBoundary = record.HasReliableFrameBoundary,
        CorrelationId = record.CorrelationId,
        TriggerBatch = record.TriggerBatch,
        ScanSequence = record.ScanSequence,
        MessageIdentity = record.MessageIdentity,
        BindingMode = record.BindingMode,
        CandidateSourceParcelId = record.CandidateSourceParcelId,
        FinalSourceParcelId = record.FinalSourceParcelId,
        DeltaMilliseconds = record.DeltaMilliseconds,
        DecisionReason = record.DecisionReason,
        FifoRecoveryMode = record.FifoRecoveryMode,
        Provider = record.Provider,
        TaskCode = record.TaskCode,
        TargetChuteCode = record.TargetChuteCode,
        DispatchedChuteCode = record.DispatchedChuteCode,
        ActualChuteCode = record.ActualChuteCode,
        IsFallback = record.IsFallback,
        IsRoutingBlocked = record.IsRoutingBlocked,
        ExceptionCode = record.ExceptionCode,
        ErrorMessage = record.ErrorMessage,
        RawPayload = record.RawPayload,
        RequestUrl = record.RequestUrl,
        RequestHeaders = record.RequestHeaders,
        RequestBody = record.RequestBody,
        ResponseBody = record.ResponseBody,
        ResponseStatusCode = record.ResponseStatusCode,
        RequestAt = record.RequestAt,
        ResponseAt = record.ResponseAt,
        ElapsedMilliseconds = record.ElapsedMilliseconds,
        ImagePath = record.ImagePath,
        ImageCamera = record.ImageCamera,
        ImageContentHash = record.ImageContentHash,
        ParcelId = record.ParcelId?.ToString(System.Globalization.CultureInfo.InvariantCulture),
        RecordedAt = record.RecordedAt,
        PartitionTime = record.PartitionTime
    };
}
